import React from 'react';
import {render,screen,fireEvent,waitFor,within} from '@testing-library/react';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
vi.mock('../../../experiments/ai-rpg-engine/card-replica/node_modules/react/index.js',()=>React);
vi.mock('../../../experiments/ai-rpg-engine/card-replica/src/main',()=>({Modal:({title,children,close}:any)=><div role="dialog" aria-label={title}><button onClick={close}>关闭</button>{children}</div>}));
import {HistoryWindowDialog} from '../../../experiments/ai-rpg-engine/card-replica/src/history-window';
import {ChatView} from '../../../experiments/ai-rpg-engine/card-replica/src/chat';
import {readClientState,emptyClientState,sendBlocked} from '../../../experiments/ai-rpg-engine/card-replica/src/session-client';
const H='rpg.history-window',config={turns:3,includeInitialCharacter:false};
const plugin={id:H,name:'历史窗口',version:'1.0.0',permissions:['session.completed.read','session.history.configure','ui.contribute'],artifactSha256:'a'.repeat(64),manifestSha256:'b'.repeat(64),installed:true};
const initial={id:'s',name:'虚构角色',characterText:'虚构',mode:'offline',revision:0,runtime:{compatible:true,code:null},historyWindow:{config,configRevision:0,pendingOperationId:null},modelSelection:{revision:0,current:{kind:'fixed',model:'fixed-model'}},turns:[],requests:{}};
beforeEach(()=>{localStorage.clear();window.history.replaceState({},'', '/rpg-app/earth/');});
afterEach(()=>vi.unstubAllGlobals());
it('settings enforce 1-50, separate snapshot switch, cancel does not save',()=>{const save=vi.fn(),close=vi.fn();render(<HistoryWindowDialog config={config} busy={false} pending={false} error="" save={save} recover={()=>{}} close={close}/>);const number=screen.getByRole('spinbutton');expect(number).toHaveValue(3);expect(screen.getByRole('checkbox')).not.toBeChecked();for(const value of ['','0','1.5','51']){fireEvent.change(number,{target:{value}});expect(screen.getByRole('button',{name:'保存'})).toBeDisabled();}fireEvent.change(number,{target:{value:'50'}});expect(screen.getByRole('button',{name:'增加回合'})).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'保存'}));expect(save).toHaveBeenCalledWith({turns:50,includeInitialCharacter:true});fireEvent.click(screen.getByRole('button',{name:'取消'}));expect(close).toHaveBeenCalledOnce();expect(save).toHaveBeenCalledOnce();});
function host({unknown=false,legacy=false,pending=false}={}){let s:any=structuredClone(initial),enabled=true;const posts:{url:string;body:any}[]=[];let attempt=0;const op={operationId:'original',expectedSessionRevision:0,expectedConfigRevision:0,turns:2,includeInitialCharacter:true};if(legacy)delete s.historyWindow;if(pending)s.historyWindow.pendingOperationId=op.operationId;
 vi.stubGlobal('fetch',vi.fn(async(url:string,opts?:RequestInit)=>{const body=opts?.body?JSON.parse(opts.body as string):null;if(body)posts.push({url,body});const ok=(x:any)=>({ok:true,json:async()=>x});
 if(url.endsWith('/api/plugins'))return ok({revision:0,plugins:[plugin]});
 if(url.includes('/plugins/')){if(legacy)return {ok:false,status:409,json:async()=>({error:'HISTORY_RUNTIME_INCOMPATIBLE'})};if(body)enabled=url.endsWith('/enable');return ok({enabled,installed:true,sessionRevision:s.revision,registryRevision:0});}
 if(url.includes('/history-window')){if(body){if(unknown&&attempt++===0)throw Error('response lost');s.historyWindow={config:{turns:body.turns,includeInitialCharacter:body.includeInitialCharacter},configRevision:1,pendingOperationId:null};s.revision=1;return ok({session:s,operation:{status:'complete'}});}return ok({compatible:!legacy,enabled,sessionRevision:s.revision,configRevision:s.historyWindow?.configRevision,config:s.historyWindow?.config,pendingOperationId:s.historyWindow?.pendingOperationId,historyPolicyRevision:(enabled?'c':'d').repeat(64),...(url.includes('?')?{operation:{status:'pending',input:op}}:{})});}
 if(url.endsWith('/model-selection'))return ok({canSelect:false});if(url.endsWith('/status'))return ok({budget:{remaining:0}});
 if(url.endsWith('/send'))return ok({...s,requests:{[body.requestId]:{status:'complete'}}});return ok(s);
 }));const view=render(<ChatView sessionId="s" exit={()=>{}} opened={()=>{}}/>);return {posts,view};}
async function settings(){fireEvent.click(await screen.findByRole('button',{name:'插件'}));const row=await screen.findByRole('region',{name:'历史窗口'});const setting=within(row).getByRole('button',{name:'设置'});await waitFor(()=>expect(setting).toBeEnabled());fireEvent.click(setting);return screen.findByRole('dialog',{name:'历史窗口'});}
it('save preserves draft, sends frozen policy token, disable restores ability to send with full policy',async()=>{const {posts}=host();await screen.findByText('开始你的第一次聊天吧');fireEvent.change(screen.getByRole('textbox'),{target:{value:'草稿保留'}});await settings();fireEvent.change(screen.getByRole('spinbutton'),{target:{value:'2'}});fireEvent.click(screen.getByRole('button',{name:'保存'}));await screen.findByText('历史窗口已保存，只影响后续发送。');expect(screen.getByRole('textbox')).toHaveValue('草稿保留');expect(posts).toHaveLength(1);expect(posts[0].body).toMatchObject({turns:2,includeInitialCharacter:false,expectedConfigRevision:0,expectedSessionRevision:0});fireEvent.click(screen.getByRole('button',{name:'插件'}));fireEvent.click(await screen.findByRole('button',{name:'停用插件'}));await screen.findByText('已安装，当前会话未启用');fireEvent.click(screen.getByRole('button',{name:'关闭'}));const send=screen.getByRole('button',{name:'发送'});await waitFor(()=>expect(send).toBeEnabled());fireEvent.click(send);await waitFor(()=>expect(posts.some(p=>p.url.endsWith('/send'))).toBe(true));expect(posts.at(-1)?.body.expectedHistoryPolicyRevision).toBe('d'.repeat(64));});
it('unknown setting survives reload, blocks sends and recovers with exactly same operation',async()=>{const {posts,view}=host({unknown:true});await screen.findByText('开始你的第一次聊天吧');fireEvent.change(screen.getByRole('textbox'),{target:{value:'仍然保留'}});await settings();fireEvent.click(screen.getByRole('button',{name:'保存'}));await screen.findByText(/设置未完成/);expect(readClientState('s').historySetting?.operationId).toBe(posts[0].body.operationId);view.unmount();render(<ChatView sessionId="s" exit={()=>{}} opened={()=>{}}/>);await screen.findByText('开始你的第一次聊天吧');expect(screen.getByRole('button',{name:'发送'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'恢复设置结果'}));await screen.findByText('历史窗口已保存，只影响后续发送。');expect(posts).toHaveLength(2);expect(posts[1].body).toEqual(posts[0].body);expect(screen.getByRole('textbox')).toHaveValue('仍然保留');expect(readClientState('s').historySetting).toBeNull();});
it('server pending settings recover from original receipt without guessing a new operation',async()=>{const {posts}=host({pending:true});await screen.findByText('开始你的第一次聊天吧');fireEvent.click(screen.getByRole('button',{name:'恢复设置结果'}));await screen.findByText('历史窗口已保存，只影响后续发送。');expect(posts[0].body.operationId).toBe('original');expect(posts).toHaveLength(1);});
it('legacy sessions have explicit incompatibility and no upgrade/settings button',async()=>{host({legacy:true});await screen.findByText('开始你的第一次聊天吧');fireEvent.click(screen.getByRole('button',{name:'插件'}));await screen.findByText('此旧版本会话不兼容，请新建会话。');expect(screen.queryByText(/部分插件状态暂不可用/)).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'设置'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'授权并启用'})).not.toBeInTheDocument();});
it('corrupt saved history operation rejects without clearing storage; pending blocks even offline',()=>{const local={...emptyClientState(),draft:'x',historySetting:{operationId:'o',expectedSessionRevision:0,expectedConfigRevision:0,turns:0,includeInitialCharacter:false}};expect(()=>readClientState('s',{getItem:()=>JSON.stringify(local)})).toThrow();expect(sendBlocked(initial as any,{...local,historySetting:{...local.historySetting,turns:1}},false)).toBe(true);});
