import React from 'react';
import {render,screen,fireEvent,waitFor,within} from '@testing-library/react';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
// The independent card keeps its own dependencies; tests use one React renderer.
vi.mock('../../../experiments/ai-rpg-engine/card-replica/node_modules/react/index.js',()=>React);
vi.mock('../../../experiments/ai-rpg-engine/card-replica/src/main',()=>({Modal:({title,children,close}:any)=><div role="dialog" aria-label={title}><button onClick={close}>关闭</button>{children}</div>}));
import {ModelPicker,priceText} from '../../../experiments/ai-rpg-engine/card-replica/src/model-picker';
import {ChatView} from '../../../experiments/ai-rpg-engine/card-replica/src/chat';
import {readClientState,writeClientState,emptyClientState,sendBlocked} from '../../../experiments/ai-rpg-engine/card-replica/src/session-client';
const A={selectionId:'a',selectionRevision:'a1',model:'google/gemini-a',name:'Gemini A',available:true};
const B={selectionId:'b',selectionRevision:'b1',model:'anthropic/claude-b',name:'Claude B',available:true};
const D={selectionId:'d',selectionRevision:'d1',model:'deepseek/d',name:'DeepSeek D',available:false};
const plugins=[{id:'rpg.model-selector',name:'模型选择',permissions:['model.catalog.read','session.model.select','ui.contribute']},{id:'rpg.branch-save',name:'分支存档',permissions:['session.completed.read']}].map(p=>({...p,version:'1.0.0',artifactSha256:'a'.repeat(64),manifestSha256:'b'.repeat(64),installed:true}));
const current={kind:'controlled' as const,model:A.model,selectionId:A.selectionId,selectionRevision:A.selectionRevision};
const base={id:'s',name:'虚构角色',characterText:'虚构',mode:'real',revision:1,runtime:{compatible:true,code:null},modelSelection:{revision:1,current},turns:[{requestId:'old',input:'开始',raw:'已有故事',html:'已有故事',at:'now',model:{actualModel:A.model,requestedModel:A.model}}],requests:{old:{status:'complete'}}};
beforeEach(()=>{localStorage.clear();window.history.replaceState({},'', '/rpg-app/earth/');HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};});
afterEach(()=>vi.unstubAllGlobals());
function picker(extra:any={}){const choose=vi.fn(),close=vi.fn();render(<ModelPicker current={current} models={[A,B,D]} loading={false} error="" locked={false} refresh={()=>{}} choose={choose} close={close} {...extra}/>);return {choose,close};}
it('approved minimal picker: brands and search intersect; click selects; unavailable stays disabled',()=>{const {choose}=picker();expect(screen.queryByText('确认选择')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Claude'}));expect(screen.queryByRole('button',{name:/Gemini A/})).not.toBeInTheDocument();fireEvent.change(screen.getByRole('searchbox'),{target:{value:'none'}});expect(screen.getByText('没有匹配的模型')).toBeInTheDocument();fireEvent.change(screen.getByRole('searchbox'),{target:{value:'Claude'}});fireEvent.click(screen.getByRole('button',{name:/Claude B/}));expect(choose).toHaveBeenCalledWith(B);fireEvent.click(screen.getByRole('button',{name:'All'}));fireEvent.change(screen.getByRole('searchbox'),{target:{value:''}});expect(screen.getByRole('button',{name:/DeepSeek D/})).toBeDisabled();});
it('close, Escape and outside cancel without saving; saving prevents dismissal and duplicate choices',()=>{const {close,choose}=picker();fireEvent(screen.getByRole('dialog'),new Event('cancel',{bubbles:false,cancelable:true}));expect(close).toHaveBeenCalledTimes(1);fireEvent.click(screen.getByRole('dialog'),{clientX:-1,clientY:-1});expect(close).toHaveBeenCalledTimes(2);expect(choose).not.toHaveBeenCalled();});
it('loading/error are honest; refresh is explicit; unverified pricing is omitted',()=>{const refresh=vi.fn();picker({error:'模型列表暂不可用',refresh});expect(screen.queryByText(B.name)).not.toBeInTheDocument();fireEvent.click(screen.getByText('刷新列表'));expect(refresh).toHaveBeenCalledTimes(1);expect(priceText({...A,pricing:{input_price:1,output_price:2}})).toBeNull();expect(priceText({...A,pricing:{source:'provider_catalog',currency:'USD',unit:'per_1m_tokens',input_price:'1',output_price:'2',observed_at:'2026-09-19T00:00:00Z'}})).toContain('目录报价 2026-09-19');});
function host(options:{unknown?:boolean;legacy?:boolean;catalog?:typeof A[];branchError?:boolean}={}){let s:any=structuredClone(base),enabled=true;const posts:{url:string;body:any}[]=[];if(options.legacy)delete s.modelSelection;
 vi.stubGlobal('fetch',vi.fn(async(url:string,opts?:RequestInit)=>{const body=opts?.body?JSON.parse(opts.body as string):null;const ok=(data:any)=>({ok:true,json:async()=>data});if(body)posts.push({url,body});
 if(url.endsWith('/api/plugins'))return ok({revision:2,plugins});
 if(url.includes('/plugins/')){if(options.branchError&&url.includes('rpg.branch-save'))return {ok:false,status:503,json:async()=>({error:'PLUGIN_FAULT'})};if(body){enabled=url.endsWith('/enable');return ok({});}return ok({enabled,installed:true,sessionRevision:1,registryRevision:2});}
 if(url.endsWith('/model-catalog'))return ok({models:options.catalog||[A,B,D]});
 if(url.endsWith('/model-selection')){if(body){if(options.unknown)throw Error('network');s={...s,modelSelection:{revision:2,current:{kind:'controlled',model:B.model,selectionId:'b',selectionRevision:'b1'}}};return ok({session:s});}return ok({modelSelection:s.modelSelection,canSelect:enabled});}
 if(url.endsWith('/status'))return ok({budget:{remaining:4}});
 if(url.endsWith('/send'))return ok({...s,requests:{...s.requests,[body.requestId]:{status:'complete'}}});
 return ok(s);
 }));render(<ChatView sessionId="s" exit={()=>{}} opened={()=>{}}/>);return posts;
}
it('selection preserves draft/history, sends exact new revision and handles reversed plugin order',async()=>{const posts=host();await screen.findByText('已有故事');fireEvent.change(screen.getByRole('textbox',{name:'对话输入'}),{target:{value:'保留草稿'}});const trigger=screen.getByRole('button',{name:'选择模型：'+A.model});await waitFor(()=>expect(trigger).toBeEnabled());fireEvent.click(trigger);fireEvent.click(await screen.findByRole('button',{name:/Claude B/}));await waitFor(()=>expect(screen.queryByRole('dialog',{name:'选择模型'})).not.toBeInTheDocument());expect(screen.getByRole('textbox')).toHaveValue('保留草稿');expect(screen.getByText(/第 1 回合/)).toHaveTextContent(A.model);expect(posts[0].body).toMatchObject({selectionId:'b',catalogRevision:'b1',selectionRevision:1,expectedSessionRevision:1});expect(posts.some(p=>p.url.endsWith('/send'))).toBe(false);fireEvent.click(screen.getByRole('button',{name:'发送'}));await waitFor(()=>expect(posts.some(p=>p.url.endsWith('/send'))).toBe(true));expect(posts.find(p=>p.url.endsWith('/send'))?.body.expectedSelectionRevision).toBe(2);
 fireEvent.click(screen.getByRole('button',{name:'插件'}));const branch=await screen.findByRole('region',{name:'分支存档'});fireEvent.click(within(branch).getByText('停用插件'));await waitFor(()=>expect(posts.some(p=>p.body.pluginId==='rpg.branch-save')).toBe(true));});
it('unknown selection survives remount and blocks sends; only explicit same-ID recovery posts again',async()=>{const posts=host({unknown:true});await screen.findByText('已有故事');const trigger=screen.getByRole('button',{name:'选择模型：'+A.model});await waitFor(()=>expect(trigger).toBeEnabled());fireEvent.click(trigger);fireEvent.click(await screen.findByRole('button',{name:/Claude B/}));await screen.findByText('恢复选择结果');expect(readClientState('s').selection?.operationId).toBe(posts[0].body.operationId);expect(screen.getByRole('button',{name:'发送'})).toBeDisabled();expect(posts).toHaveLength(1);fireEvent.click(screen.getByText('恢复选择结果'));await waitFor(()=>expect(posts).toHaveLength(2));expect(posts[1].body).toEqual(posts[0].body);});
it('old sessions do not pretend to support model changes or add v2 fields to send',async()=>{const posts=host({legacy:true});await screen.findByText('已有故事');expect(screen.queryByRole('button',{name:/选择模型：/})).not.toBeInTheDocument();fireEvent.change(screen.getByRole('textbox'),{target:{value:'继续'}});fireEvent.click(screen.getByRole('button',{name:'发送'}));await waitFor(()=>expect(posts).toHaveLength(1));expect(posts[0].body).not.toHaveProperty('expectedSelectionRevision');});
it('selection uncertainty survives storage and prevents core sending without destroying the draft',()=>{const selection={operationId:'op',expectedSessionRevision:1,selectionRevision:1,selectionId:'b',catalogRevision:'b1'},state={...emptyClientState(),draft:'未发',selection};writeClientState('s',state);expect(readClientState('s')).toEqual(state);expect(sendBlocked(base,state,false,4)).toBe(true);localStorage.setItem('earth-chat-v1:s',JSON.stringify({...state,selection:{}}));expect(()=>readClientState('s')).toThrow();});

it('saving disables all model writes and prevents dismissal',()=>{const {choose,close}=picker({locked:true});expect(screen.getByRole('button',{name:/Claude B/})).toBeDisabled();fireEvent(screen.getByRole('dialog'),new Event('cancel',{cancelable:true}));expect(close).not.toHaveBeenCalled();expect(choose).not.toHaveBeenCalled();});
it('initial loading and an empty catalog show no invented models or metrics',()=>{picker({models:[],loading:true});expect(screen.getByText('正在加载…')).toBeInTheDocument();expect(screen.queryByText('可用')).not.toBeInTheDocument();expect(screen.queryByText(/出字率|价格系数|API/)).not.toBeInTheDocument();});

it('one Escape cancels even with a nonempty native search field',()=>{const {close,choose}=picker();fireEvent.change(screen.getByRole('searchbox'),{target:{value:'none'}});fireEvent.keyDown(screen.getByRole('searchbox'),{key:'Escape'});expect(close).toHaveBeenCalledTimes(1);expect(choose).not.toHaveBeenCalled();});

it('a missing selected model in an empty fresh catalog blocks send without silently changing choice',async()=>{host({catalog:[]});await screen.findByText('已有故事');fireEvent.change(screen.getByRole('textbox'),{target:{value:'保留'}});await screen.findByText('当前模型暂不可用，请选择其他模型。');expect(screen.getByRole('button',{name:'发送'})).toBeDisabled();expect(screen.getByRole('button',{name:'选择模型：'+A.model})).toBeInTheDocument();});
it('one plugin status failure keeps the other available and reports unknown status honestly',async()=>{host({branchError:true});await screen.findByText('已有故事');const trigger=screen.getByRole('button',{name:'选择模型：'+A.model});await waitFor(()=>expect(trigger).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'插件'}));const branch=await screen.findByRole('region',{name:'分支存档'});expect(within(branch).getByText('状态待核对')).toBeInTheDocument();expect(within(branch).queryByText('尚未安装')).not.toBeInTheDocument();expect(within(screen.getByRole('region',{name:'模型选择'})).getByRole('button',{name:'停用插件'})).toBeEnabled();});
