import React from 'react';
import {render,screen,fireEvent,waitFor,act} from '@testing-library/react';
import {it,expect,vi,afterEach,beforeEach} from 'vitest';
vi.mock('../../../experiments/ai-rpg-engine/card-replica/node_modules/react/index.js',async()=>await import('react'));
vi.mock('../../../experiments/ai-rpg-engine/card-replica/src/main',()=>({Modal:({title,children,close}:any)=><div role="dialog" aria-label={title} onKeyDown={e=>{if(e.key==='Escape')close();}}><button onClick={close}>关闭浮层</button>{children}</div>}));
import {MemoryPalaceDialog,useMemoryPalace} from '../../../experiments/ai-rpg-engine/card-replica/src/memory-palace';
import type {MemoryStatus} from '../../../experiments/ai-rpg-engine/card-replica/src/memory-palace';
const initial:MemoryStatus={compatible:true,enabled:true,busy:false,sessionRevision:3,memoryRevision:2,config:{model:null},entries:[],processedThrough:0,totalTurns:0,pendingOperationId:null,blocked:null,operations:{},originalOutputs:[],effectivePolicy:{revision:'a'.repeat(64)},maxCalls:2,updateMaxCalls:0,lastRecall:null};
const defaults={sessionId:'s',busy:false,pending:false,error:'',perform:vi.fn(async()=>true),recover:vi.fn(),close:vi.fn()};
beforeEach(()=>{localStorage.clear();vi.clearAllMocks();window.history.replaceState({},'', '/rpg-app/earth/');});afterEach(()=>vi.unstubAllGlobals());
function fill(){fireEvent.change(screen.getByRole('textbox',{name:'名称'}),{target:{value:'手记'}});fireEvent.change(screen.getByRole('textbox',{name:'关键词'}),{target:{value:'阿宁，Library'}});fireEvent.change(screen.getByRole('textbox',{name:'内容'}),{target:{value:'阿宁约好在图书馆见面；尚未赴约。'}});}
it('manual creation validates roles, duplicate keywords and Unicode limit; saves original base revision without dispatch',async()=>{const perform=vi.fn(async()=>true);render(<MemoryPalaceDialog {...defaults} perform={perform} status={initial}/>);fireEvent.click(screen.getByRole('button',{name:'＋ 新增'}));fill();fireEvent.change(screen.getByRole('textbox',{name:'内容'}),{target:{value:'😀'.repeat(2001)}});expect(screen.getByRole('button',{name:'保存'})).toBeDisabled();fill();fireEvent.click(screen.getByRole('checkbox',{name:'用户'}));fireEvent.click(screen.getByRole('checkbox',{name:'AI'}));expect(screen.getByRole('button',{name:'保存'})).toBeDisabled();fireEvent.click(screen.getByRole('checkbox',{name:'用户'}));fireEvent.change(screen.getByRole('textbox',{name:'关键词'}),{target:{value:'Library,library'}});expect(screen.getByRole('button',{name:'保存'})).toBeDisabled();fill();fireEvent.click(screen.getByRole('button',{name:'保存'}));await waitFor(()=>expect(perform).toHaveBeenCalledOnce());expect(perform.mock.calls[0]).toEqual(['edit',{expectedSessionRevision:3,expectedMemoryRevision:2,change:{action:'create',value:{name:'手记',keywords:['阿宁','Library'],match:'any',roles:['user'],content:'阿宁约好在图书馆见面；尚未赴约。',enabled:true}}}]);});
it('Esc asks to discard unsaved input; cancelling does not call provider or save',()=>{render(<MemoryPalaceDialog {...defaults} status={initial}/>);fireEvent.click(screen.getByRole('button',{name:'＋ 新增'}));fill();fireEvent.keyDown(screen.getByRole('dialog'),{key:'Escape'});expect(screen.getByRole('alertdialog')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'继续编辑'}));expect(screen.getByRole('textbox',{name:'名称'})).toHaveValue('手记');fireEvent.click(screen.getByRole('button',{name:'取消'}));fireEvent.click(screen.getByRole('button',{name:'放弃修改'}));expect(screen.getByRole('button',{name:'＋ 新增'})).toBeInTheDocument();expect(defaults.perform).not.toHaveBeenCalled();});
it('intervening library revision preserves edited draft and prevents stale write',()=>{const v=render(<MemoryPalaceDialog {...defaults} status={initial}/>);fireEvent.click(screen.getByRole('button',{name:'＋ 新增'}));fill();v.rerender(<MemoryPalaceDialog {...defaults} status={{...initial,memoryRevision:3,sessionRevision:4}}/>);expect(screen.getByRole('textbox',{name:'名称'})).toHaveValue('手记');expect(screen.getByRole('button',{name:'保存'})).toBeDisabled();});
it('unknown task offers only original recovery and blocks edits',()=>{render(<MemoryPalaceDialog {...defaults} status={initial} pending/>);expect(screen.getByRole('button',{name:'＋ 新增'})).toBeDisabled();expect(screen.getByRole('button',{name:'选择记忆模型'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'恢复操作结果'}));expect(defaults.recover).toHaveBeenCalledOnce();});
it('protected entry exposes revisions and restore; raw markup is text',()=>{const value={name:'阿宁',keywords:['阿宁'],match:'any' as const,roles:['user' as const],content:'<script>bad()</script>',enabled:false};const entry={id:'a',version:1,value,protected:true,deleted:false,origin:'manual',revisions:[{version:1,value,protected:true,deleted:false,source:{kind:'manual'}}]};render(<MemoryPalaceDialog {...defaults} status={{...initial,entries:[entry]}}/>);expect(screen.getByText('人工保护 · 已停用')).toBeInTheDocument();expect(document.querySelector('script')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'解除保护',hidden:true}));expect(defaults.perform).toHaveBeenCalledWith('edit',{expectedSessionRevision:3,expectedMemoryRevision:2,change:{action:'protect',id:'a',baseVersion:1,protected:false}});});
it('unknown settings survive remount and recover with same ID; refresh never replays',async()=>{const posts:any[]=[],session:any={id:'s',revision:3,memoryPalace:{supported:true}};vi.stubGlobal('fetch',vi.fn(async(url:string,o?:RequestInit)=>{if(o?.body){posts.push({url,body:JSON.parse(o.body as string)});if(url.endsWith('/settings'))throw Error();return {ok:true,json:async()=>({session,operation:{status:'complete'}})};}return {ok:true,json:async()=>initial};}));function Harness(){const h=useMemoryPalace(session,()=>{});return <><button onClick={()=>h.perform('settings',{selectionId:'offline',catalogRevision:'v1'})}>写入</button><button onClick={()=>h.recover()}>恢复</button><span>{h.unconfirmed?'待核对':'无待办'}</span><p>{h.error}</p></>;}const v=render(<Harness/>);fireEvent.click(screen.getByRole('button',{name:'写入'}));await screen.findByText(/操作未完成/);expect(posts).toHaveLength(1);v.unmount();render(<Harness/>);await screen.findByText('待核对');fireEvent.click(screen.getByRole('button',{name:'恢复'}));await screen.findByText(/已核对保存/);expect(posts).toHaveLength(2);expect(posts[1].url).toMatch(/recover$/);expect(posts[1].body.operationId).toBe(posts[0].body.operationId);});
it('late old-session polling cannot overwrite the next session',async()=>{let resolveOld:(v:any)=>void=()=>{};vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.includes('/old/')?new Promise(r=>{resolveOld=r;}):{ok:true,json:async()=>({...initial,processedThrough:7})}));function Harness({id}:{id:string}){const h=useMemoryPalace({id,revision:3,memoryPalace:{supported:true}} as any,()=>{});return <span>{h.status?.processedThrough??'waiting'}</span>;}const v=render(<Harness id="old"/>);v.rerender(<Harness id="new"/>);await screen.findByText('7');await act(async()=>resolveOld({ok:true,json:async()=>({...initial,processedThrough:1})}));expect(screen.getByText('7')).toBeInTheDocument();});
it('successful refresh clears read failure without hiding unknown writes',async()=>{let down=true;const session:any={id:'s',revision:3,memoryPalace:{supported:true}};vi.stubGlobal('fetch',vi.fn(async()=>{if(down)throw Error();return {ok:true,json:async()=>initial};}));function Harness(){const h=useMemoryPalace(session,()=>{});return <><button onClick={()=>h.refresh()}>刷新</button><p>{h.error}</p><span>{h.status?'可用':'不可用'}</span></>;}render(<Harness/>);await screen.findByText(/状态暂不可用/);down=false;fireEvent.click(screen.getByRole('button',{name:'刷新'}));await screen.findByText('可用');expect(screen.queryByText(/状态暂不可用/)).not.toBeInTheDocument();});

it('disabled palace says read-only; recall uses the historical name and precise capacity reason',()=>{const value={name:'后来改名',keywords:['阿宁'],match:'any' as const,roles:['user' as const],content:'正文',enabled:true};const entry={id:'a',version:2,value,protected:true,deleted:false,origin:'manual',revisions:[{version:1,value:{...value,name:'原来名字'},protected:true,deleted:false,source:{kind:'manual'}},{version:2,value,protected:true,deleted:false,source:{kind:'manual'}}]};render(<MemoryPalaceDialog {...defaults} status={{...initial,enabled:false,entries:[entry],lastRecall:{results:[{id:'a',version:1,selected:false,reason:'body-limit'}]}}}/>);expect(screen.getByText(/当前未启用，仅查看/)).toBeInTheDocument();expect(screen.getByText(/原来名字.*已达携带正文上限/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'＋ 新增'})).toBeDisabled();});
