import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import PageContainer from '../components/PageContainer';
type Card={id:string;title:string;model:string;enabled:boolean;remaining:number;used:number};
export default function RpgPage(){
 const {cardId}=useParams();const [cards,setCards]=useState<Card[]>([]),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch('/rpg-app/api/status',{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('RPG 服务暂不可用，请稍后刷新。');return r.json();}).then(x=>setCards(x.cards)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[cardId]);
 if(cardId&&['earth','rpg05'].includes(cardId))return <div className="flex min-h-0 flex-1 flex-col"><header className="flex flex-wrap items-center gap-4 border-b border-white/10 px-5 py-3"><Link to="/rpg" className="text-sm text-zinc-300 hover:text-white focus-visible:outline focus-visible:outline-2">← 返回 RPG</Link><h1 className="text-base font-medium text-white">{cardId==='earth'?'地球 OL · 人生模拟器':'行间 · 多世界 RPG'}</h1>{cardId==='rpg05'&&<span className="text-xs text-amber-200">半成品</span>}</header><iframe title={cardId==='earth'?'地球 OL 角色与会话':'行间角色与会话'} src={'/rpg-app/'+cardId+'/'} className="w-full flex-1 border-0 bg-zinc-950" style={{minHeight:'calc(100dvh - 130px)'}} allow="clipboard-write"/></div>;
 return <PageContainer><div className="mx-auto max-w-5xl py-8"><Link to="/studio" className="text-sm text-zinc-400 hover:text-white">← Studio</Link><h1 className="mt-5 text-3xl font-semibold tracking-tight text-white">RPG</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-zinc-300">选择一张卡片，创建角色，开始或继续你的故事。角色草稿分别保存，已生成的原文可从各自的历史中恢复。</p>{error&&<p role="alert" className="mt-6 text-amber-200">{error}</p>}<div className="mt-8 divide-y divide-white/10 border-y border-white/10">{[{id:'earth',title:'地球 OL · 人生模拟器',description:'从出生、家世、天赋与命运开始一世人生，可选择表世界或深层世界。',label:'作者卡片复刻 · 已通过本轮人工验收'},{id:'rpg05',title:'行间 · 多世界 RPG',description:'选择世界与开局，配置身份、天赋和随身物品，以轻量文本推进故事。',label:'半成品 · 调优与完整质量验收延期'}].map(item=>{const status=cards.find(c=>c.id===item.id);return <section key={item.id} className="flex flex-col justify-between gap-6 py-8 sm:flex-row sm:items-center"><div><p className="text-xs text-zinc-400">{item.label}</p><h2 className="mt-2 text-xl font-medium text-white">{item.title}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-300">{item.description}</p><p className="mt-3 text-xs text-zinc-400">{status?`${status.model} · ${status.enabled?'正式调用已启用':'正式调用未配置'} · 本轮剩余 ${status.remaining} 次`:'正在读取调用状态…'}</p></div><Link to={'/rpg/'+item.id} className="shrink-0 self-start rounded-lg border border-white/20 px-5 py-2.5 text-sm text-white transition-colors hover:bg-white/10 focus-visible:outline focus-visible:outline-2 sm:self-auto">进入卡片 →</Link></section>;})}</div><p className="mt-6 text-sm leading-6 text-zinc-400">本轮每张卡自动实测一次，随后等待人工审阅。失败和取消也计入额度，刷新页面不会重新发送。</p><Link to="/help" className="mt-4 inline-block text-sm text-blue-300 hover:text-blue-200">查看帮助中心</Link></div></PageContainer>;
}
