import {render,screen,fireEvent,waitFor,within} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {afterEach,it,expect,vi} from 'vitest';
import RpgPluginsPage from './RpgPluginsPage';
import RpgPage from './RpgPage';
afterEach(()=>vi.unstubAllGlobals());
const plugin={id:'rpg.branch-save',name:'分支存档',version:'1.0.0',installed:false,compatibleInstallation:false,artifactSha256:'a'.repeat(64),manifestSha256:'b'.repeat(64),permissions:['session.completed.read','session.branch.prepare','ui.contribute'],source:'reviewed first-party',license:'UNLICENSED'};
it('discovers, installs, filters and uninstalls without enabling or deleting conversations',async()=>{let installed=false;const post:unknown[]=[];vi.stubGlobal('fetch',vi.fn(async(url:string,options?:RequestInit)=>{if(options){post.push(JSON.parse(options.body as string));installed=url.endsWith('/install');return {ok:true,json:async()=>({})};}return {ok:true,json:async()=>({revision:installed?1:0,plugins:[{...plugin,installed}]})};}));render(<MemoryRouter><RpgPluginsPage/></MemoryRouter>);await screen.findByText('分支存档');fireEvent.click(screen.getByRole('button',{name:'安装插件'}));await screen.findByRole('button',{name:'卸载插件'});expect(post).toHaveLength(1);expect(post[0]).toMatchObject({pluginId:plugin.id,version:'1.0.0',artifactSha256:plugin.artifactSha256,expectedRegistryRevision:0});expect(post[0]).not.toHaveProperty('sessionId');fireEvent.click(screen.getByRole('button',{name:'已安装 1'}));fireEvent.click(screen.getByRole('button',{name:'卸载插件'}));await screen.findByText(/还没有安装插件/);expect(post).toHaveLength(2);expect(screen.getByText(/原对话和分支保留，重新安装/)).toBeInTheDocument();});
it('failure remains recoverable and does not auto retry',async()=>{const fetcher=vi.fn().mockRejectedValue(Error('offline'));vi.stubGlobal('fetch',fetcher);render(<MemoryRouter><RpgPluginsPage/></MemoryRouter>);await screen.findByRole('alert');expect(fetcher).toHaveBeenCalledTimes(1);fireEvent.click(screen.getByRole('button',{name:'刷新状态'}));await waitFor(()=>expect(fetcher).toHaveBeenCalledTimes(2));});
it('RPG entrance links to optional market without changing Studio layout',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({cards:[]})}));render(<MemoryRouter><RpgPage/></MemoryRouter>);expect(screen.getByRole('link',{name:'插件市场'})).toHaveAttribute('href','/rpg/plugins');expect(screen.getByText(/额度内连续游玩/)).toBeInTheDocument();await waitFor(()=>expect(fetch).toHaveBeenCalledTimes(1));});

it('two plugins retain distinct descriptions, permissions and installation IDs',async()=>{let installed=false;const posts:any[]=[];const selector={...plugin,id:'rpg.model-selector',name:'模型选择',permissions:['model.catalog.read','session.model.select','ui.contribute']};vi.stubGlobal('fetch',vi.fn(async(url:string,options?:RequestInit)=>{if(options){posts.push(JSON.parse(options.body as string));installed=url.endsWith('/install');return {ok:true,json:async()=>({})};}return {ok:true,json:async()=>({revision:1,plugins:[{...selector,installed},plugin]})};}));render(<MemoryRouter><RpgPluginsPage/></MemoryRouter>);const row=await screen.findByRole('article',{name:'模型选择'});expect(within(row).getByText('查看可供当前卡片选择的模型。')).toBeInTheDocument();expect(within(row).queryByText(/读取你启用插件的会话中已完成的回合/)).not.toBeInTheDocument();fireEvent.click(within(row).getByRole('button',{name:'安装插件'}));await within(row).findByText('已安装');expect(posts[0].pluginId).toBe('rpg.model-selector');expect(within(screen.getByRole('article',{name:'分支存档'})).getByText('尚未安装')).toBeInTheDocument();fireEvent.click(within(row).getByRole('button',{name:'卸载插件'}));await screen.findByText(/已卸载。已选模型和历史保留/);expect(posts).toHaveLength(2);});
