import { useEffect, useId, useMemo, useRef, useState, type RefObject } from "react";
import { createPortal } from "react-dom";
import type { WorkflowNode, WorkflowValue, WorkflowVariableDeclaration, WorkflowVariableDeclarationKind, WorkflowVariableDeclarationValueType } from "../../types/workflow";
import { validateWorkflowVariableDeclaration, type WorkflowVariableAvailability, type WorkflowVariableDescriptor, type WorkflowVariableRenamePlan, type WorkflowVariableSourceKind, type WorkflowVariableValueType } from "./workflowVariables";

const STATUS_ORDER: Record<WorkflowVariableAvailability, number> = { available: 0, conflict: 1, conditional: 2, unavailable: 3, inventory: 4 };
function statusCopy(status: WorkflowVariableAvailability) { return status === "available" ? "可引用" : status === "conditional" ? "条件可用" : status === "unavailable" ? "不可引用" : status === "conflict" ? "名称冲突" : "目录项"; }
function statusClass(status: WorkflowVariableAvailability) { return status === "available" ? "border-emerald-300/25 bg-emerald-300/10 text-emerald-100" : status === "conditional" ? "border-amber-300/25 bg-amber-300/10 text-amber-100" : status === "conflict" ? "border-rose-300/30 bg-rose-300/10 text-rose-100" : "border-white/10 bg-white/[0.05] text-slate-300"; }
function typeCopy(type: WorkflowVariableValueType) { return type === "text" ? "文本" : type === "number" ? "数字" : type === "boolean" ? "布尔" : type === "json" ? "结构化数据" : type === "file_asset" ? "文件资产" : "动态类型"; }
function sourceCopy(kind: WorkflowVariableSourceKind) { return kind === "workflow_input" ? "工作流输入" : kind === "workflow_constant" ? "工作流常量" : kind === "file_asset" ? "文件输入" : "节点输出"; }
function focusableElements(container: HTMLElement) { return Array.from(container.querySelectorAll<HTMLElement>("button:not([disabled]), input:not([disabled]), textarea:not([disabled]), select:not([disabled]), [href], [tabindex]:not([tabindex='-1'])")).filter((element) => !element.hasAttribute("aria-hidden")); }
function defaultValueText(declaration: WorkflowVariableDeclaration | null) { if (!declaration || declaration.defaultValue === undefined) return ""; return declaration.valueType === "json" ? JSON.stringify(declaration.defaultValue, null, 2) : String(declaration.defaultValue); }
function parseDefaultValue(raw: string, kind: WorkflowVariableDeclarationKind, valueType: WorkflowVariableDeclarationValueType): { value?: WorkflowValue; error?: string } {
  if (!raw.trim() && kind === "input") return {};
  if (!raw.trim()) return { error: "常量必须设置值。" };
  if (valueType === "text") return { value: raw };
  if (valueType === "number") { const value = Number(raw); return Number.isFinite(value) ? { value } : { error: "请输入有限数字。" }; }
  if (valueType === "boolean") return raw === "true" ? { value: true } : raw === "false" ? { value: false } : { error: "请选择 true 或 false。" };
  try { return { value: JSON.parse(raw) as WorkflowValue }; } catch { return { error: "JSON 格式无效。" }; }
}
function newDeclaration(): WorkflowVariableDeclaration { const suffix = typeof crypto !== "undefined" && "randomUUID" in crypto ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`; return { id: `wfvar_${suffix}`, name: "", kind: "input", valueType: "text", description: "" }; }
type CenterView = "list" | "detail" | "form" | "rename";

export default function WorkflowVariableCenter({ open, variables, declarations, nodes, selectedNode, triggerRef, onClose, onLocateSource, onCreate, onUpdate, onDelete, onPlanRename, onApplyRename }: {
  open: boolean; variables: WorkflowVariableDescriptor[]; declarations: WorkflowVariableDeclaration[]; nodes: WorkflowNode[]; selectedNode: WorkflowNode | null; triggerRef: RefObject<HTMLButtonElement | null>; onClose: () => void; onLocateSource: (nodeId: string) => void; onCreate: (declaration: WorkflowVariableDeclaration) => void; onUpdate: (declaration: WorkflowVariableDeclaration) => void; onDelete: (declarationId: string) => string | null; onPlanRename: (oldName: string, newName: string) => WorkflowVariableRenamePlan; onApplyRename: (plan: WorkflowVariableRenamePlan) => void;
}) {
  const titleId = useId(); const panelRef = useRef<HTMLElement>(null); const searchRef = useRef<HTMLInputElement>(null);
  const [query, setQuery] = useState(""); const [view, setView] = useState<CenterView>("list"); const [selectedName, setSelectedName] = useState(""); const [draft, setDraft] = useState<WorkflowVariableDeclaration | null>(null); const [defaultRaw, setDefaultRaw] = useState(""); const [formError, setFormError] = useState(""); const [renameValue, setRenameValue] = useState("");
  const selectedVariable = variables.find((variable) => variable.name === selectedName) ?? null;
  const selectedDeclaration = declarations.find((declaration) => declaration.name === selectedName) ?? null;
  useEffect(() => {
    if (!open) return;
    const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden";
    if (view === "list") window.requestAnimationFrame(() => searchRef.current?.focus());
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") { event.preventDefault(); if (view !== "list") { setView("list"); window.requestAnimationFrame(() => searchRef.current?.focus()); } else { onClose(); window.requestAnimationFrame(() => triggerRef.current?.focus()); } return; }
      if (event.key !== "Tab" || !panelRef.current) return; const items = focusableElements(panelRef.current); if (!items.length) return; const first = items[0]; const last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
    };
    document.addEventListener("keydown", handleKeyDown); return () => { document.body.style.overflow = previousOverflow; document.removeEventListener("keydown", handleKeyDown); };
  }, [onClose, open, triggerRef, view]);
  useEffect(() => { if (!open) return; setQuery(""); setView("list"); setSelectedName(""); setFormError(""); }, [open]);
  const filtered = useMemo(() => { const normalized = query.trim().toLocaleLowerCase("zh-CN"); return variables.filter((variable) => !normalized || variable.name.toLocaleLowerCase("zh-CN").includes(normalized) || variable.sources.some((source) => source.nodeTitle.toLocaleLowerCase("zh-CN").includes(normalized))).sort((left, right) => STATUS_ORDER[left.availability] - STATUS_ORDER[right.availability] || left.name.localeCompare(right.name, "zh-CN")); }, [query, variables]);
  const renamePlan = useMemo(() => selectedName && renameValue ? onPlanRename(selectedName, renameValue) : null, [onPlanRename, renameValue, selectedName]);
  if (!open || typeof document === "undefined") return null;
  const closeAndRestoreFocus = () => { onClose(); window.requestAnimationFrame(() => triggerRef.current?.focus()); };
  const openCreate = () => { setDraft(newDeclaration()); setDefaultRaw(""); setFormError(""); setView("form"); };
  const openEdit = () => { if (!selectedDeclaration) return; setDraft({ ...selectedDeclaration }); setDefaultRaw(defaultValueText(selectedDeclaration)); setFormError(""); setView("form"); };
  const saveDraft = () => {
    if (!draft) return; const parsed = parseDefaultValue(defaultRaw, draft.kind, draft.valueType); if (parsed.error) { setFormError(parsed.error); return; }
    const candidate: WorkflowVariableDeclaration = { ...draft, name: draft.name.trim(), description: draft.description?.trim() || undefined, ...(parsed.value === undefined ? { defaultValue: undefined } : { defaultValue: parsed.value }) };
    const errors = validateWorkflowVariableDeclaration(candidate, declarations, nodes); if (errors.length) { setFormError(errors.join(" ")); return; }
    if (declarations.some((item) => item.id === candidate.id)) onUpdate(candidate); else onCreate(candidate); setSelectedName(candidate.name); setView("detail");
  };
  const headerTitle = view === "list" ? "工作流变量" : view === "detail" ? selectedName : view === "rename" ? "安全改名" : draft && declarations.some((item) => item.id === draft.id) ? "编辑变量" : "新建变量";
  return createPortal(
    <div className="fixed inset-0 z-[80]">
      <button aria-label="关闭变量中心" className="absolute inset-0 cursor-default bg-ink-950/68 backdrop-blur-[2px]" onClick={closeAndRestoreFocus} tabIndex={-1} type="button" />
      <aside aria-labelledby={titleId} aria-modal="true" className="absolute inset-x-0 bottom-0 flex max-h-[88dvh] flex-col overflow-hidden rounded-t-2xl border border-white/10 bg-[#101827] shadow-panel sm:inset-y-0 sm:left-auto sm:right-0 sm:max-h-none sm:w-[min(31rem,94vw)] sm:rounded-none sm:rounded-l-2xl" ref={panelRef} role="dialog">
        <header className="border-b border-white/10 px-5 py-4">
          <div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2">{view !== "list" ? <button aria-label="返回变量列表" className="inline-flex h-9 w-9 items-center justify-center rounded-full text-slate-300 hover:bg-white/[0.07]" onClick={() => setView("list")} type="button">←</button> : null}<h2 className="truncate text-base font-semibold text-white" id={titleId}>{headerTitle}</h2></div><p className="mt-1 text-xs leading-5 text-slate-400">{selectedNode ? `当前节点：${selectedNode.data.title}` : "输入与常量属于当前工作流；节点输出保持只读。"}</p></div><button aria-label="关闭工作流变量" className="inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-full text-xl text-slate-300 hover:bg-white/[0.07] focus:ring-4 focus:ring-brand-300/15" onClick={closeAndRestoreFocus} type="button">×</button></div>
          {view === "list" ? <div className="mt-4 flex gap-2"><label className="min-w-0 flex-1"><span className="sr-only">搜索变量或来源节点</span><input className="h-11 w-full rounded-lg border border-white/10 bg-[#0b1220] px-3 text-sm text-white outline-none placeholder:text-slate-400 focus:border-brand-300/55" onChange={(event) => setQuery(event.target.value)} placeholder="搜索变量或来源节点" ref={searchRef} value={query} /></label><button className="min-h-11 shrink-0 rounded-full bg-hire-300 px-4 text-sm font-semibold text-ink-950 hover:bg-hire-200" onClick={openCreate} type="button">新建</button></div> : null}
        </header>
        <div className="min-h-0 flex-1 overflow-y-auto">
          {view === "list" ? filtered.length === 0 ? <div className="px-6 py-12 text-center text-sm text-slate-400">没有匹配的变量。</div> : <ul className="divide-y divide-white/[0.07]">{filtered.map((variable) => <li key={variable.name}><button className="w-full px-5 py-4 text-left transition hover:bg-white/[0.035] focus:ring-2 focus:ring-inset focus:ring-brand-300/35" onClick={() => { setSelectedName(variable.name); setView("detail"); }} type="button"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><code className="break-all text-sm font-semibold text-brand-100">{variable.name}</code><p className="mt-1 text-[11px] text-slate-500">{typeCopy(variable.valueType)} · {variable.references.length} 处引用</p></div><span className={`shrink-0 rounded-full border px-2.5 py-1 text-[11px] font-semibold ${statusClass(variable.availability)}`}>{statusCopy(variable.availability)}</span></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-400">{variable.availabilityReason}</p></button></li>)}</ul> : null}
          {view === "detail" && selectedVariable ? <div className="space-y-5 p-5">
            <div className="rounded-xl border border-white/10 bg-white/[0.035] p-4"><div className="flex flex-wrap gap-2"><span className={`rounded-full border px-2.5 py-1 text-[11px] font-semibold ${statusClass(selectedVariable.availability)}`}>{statusCopy(selectedVariable.availability)}</span><span className="rounded-full border border-white/10 px-2.5 py-1 text-[11px] text-slate-300">{typeCopy(selectedVariable.valueType)}</span></div><p className="mt-3 text-xs leading-5 text-slate-400">{selectedVariable.availabilityReason}</p>{selectedDeclaration?.description ? <p className="mt-2 text-sm leading-6 text-slate-200">{selectedDeclaration.description}</p> : null}</div>
            <section><h3 className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">来源</h3><div className="mt-2 space-y-2">{selectedVariable.sources.map((source) => source.declarationId ? <div className="rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2" key={source.declarationId}><p className="text-sm font-semibold text-slate-200">{source.nodeTitle}</p><p className="mt-1 text-[11px] text-slate-500">{sourceCopy(source.sourceKind)}</p></div> : <button className="flex min-h-11 w-full items-center justify-between rounded-lg border border-white/10 bg-white/[0.03] px-3 text-left text-sm text-slate-200 hover:bg-white/[0.06]" key={`${source.nodeId}:${source.field}`} onClick={() => onLocateSource(source.nodeId)} type="button"><span className="truncate">{source.nodeTitle}</span><span className="text-[11px] text-slate-500">定位</span></button>)}</div></section>
            <section><h3 className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">引用 {selectedVariable.references.length} 处</h3><div className="mt-2 space-y-2">{selectedVariable.references.length === 0 ? <p className="rounded-lg border border-dashed border-white/10 px-3 py-5 text-center text-xs text-slate-500">暂无引用。</p> : selectedVariable.references.map((reference) => <button className="flex min-h-11 w-full items-center justify-between gap-3 rounded-lg border border-white/10 bg-white/[0.03] px-3 text-left hover:bg-white/[0.06]" key={`${reference.nodeId}:${reference.field}:${reference.mode}`} onClick={() => onLocateSource(reference.nodeId)} type="button"><span className="min-w-0"><span className="block truncate text-sm text-slate-200">{reference.nodeTitle}</span><span className="block truncate text-[11px] text-slate-500">{reference.field} · {reference.mode}</span></span><span className={`shrink-0 text-[11px] ${reference.issue ? "text-amber-200" : "text-slate-500"}`}>{reference.issue ? "需处理" : "定位"}</span></button>)}</div></section>
            {selectedDeclaration ? <div className="flex flex-wrap gap-2 border-t border-white/10 pt-4"><button className="min-h-11 rounded-full border border-white/15 px-4 text-sm font-semibold text-slate-200 hover:bg-white/[0.06]" onClick={openEdit} type="button">编辑</button><button className="min-h-11 rounded-full border border-brand-300/30 px-4 text-sm font-semibold text-brand-100 hover:bg-brand-300/10" onClick={() => { setRenameValue(selectedName); setView("rename"); }} type="button">改名</button><button className="min-h-11 rounded-full border border-rose-300/25 px-4 text-sm font-semibold text-rose-100 hover:bg-rose-300/10 disabled:opacity-50" disabled={selectedVariable.references.length > 0} onClick={() => { const error = onDelete(selectedDeclaration.id); if (error) setFormError(error); else setView("list"); }} type="button">删除</button>{selectedVariable.references.length > 0 ? <p className="w-full text-xs leading-5 text-amber-200">仍有引用，清空后才能删除。</p> : null}</div> : null}
          </div> : null}
          {view === "form" && draft ? <div className="space-y-4 p-5">
            <label className="block text-xs font-semibold text-slate-300">名称<input className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-[#0b1220] px-3 font-mono text-sm text-white outline-none focus:border-brand-300/55 disabled:text-slate-500" disabled={declarations.some((item) => item.id === draft.id)} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="customer_id" value={draft.name} /></label>
            <div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-300">种类<select className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-[#0b1220] px-3 text-sm text-white" onChange={(event) => setDraft({ ...draft, kind: event.target.value as WorkflowVariableDeclarationKind })} value={draft.kind}><option value="input">工作流输入</option><option value="constant">常量</option></select></label><label className="text-xs font-semibold text-slate-300">类型<select className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-[#0b1220] px-3 text-sm text-white" onChange={(event) => { setDraft({ ...draft, valueType: event.target.value as WorkflowVariableDeclarationValueType }); setDefaultRaw(""); }} value={draft.valueType}><option value="text">文本</option><option value="number">数字</option><option value="boolean">布尔</option><option value="json">JSON</option></select></label></div>
            <label className="block text-xs font-semibold text-slate-300">{draft.kind === "constant" ? "常量值" : "默认值（可选）"}{draft.valueType === "boolean" ? <select className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-[#0b1220] px-3 text-sm text-white" onChange={(event) => setDefaultRaw(event.target.value)} value={defaultRaw}>{draft.kind === "input" ? <option value="">不设置</option> : null}<option value="true">true</option><option value="false">false</option></select> : draft.valueType === "json" ? <textarea className="mt-2 min-h-32 w-full rounded-lg border border-white/10 bg-[#0b1220] px-3 py-2 font-mono text-xs leading-5 text-white outline-none focus:border-brand-300/55" onChange={(event) => setDefaultRaw(event.target.value)} placeholder='{"key":"value"}' value={defaultRaw} /> : <input className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-[#0b1220] px-3 text-sm text-white outline-none focus:border-brand-300/55" onChange={(event) => setDefaultRaw(event.target.value)} value={defaultRaw} />}</label>
            <label className="block text-xs font-semibold text-slate-300">说明（可选）<textarea className="mt-2 min-h-24 w-full rounded-lg border border-white/10 bg-[#0b1220] px-3 py-2 text-sm leading-6 text-white outline-none focus:border-brand-300/55" maxLength={500} onChange={(event) => setDraft({ ...draft, description: event.target.value })} value={draft.description ?? ""} /></label>
            {formError ? <p aria-live="assertive" className="text-xs leading-5 text-rose-200" role="alert">{formError}</p> : null}<button className="min-h-11 w-full rounded-full bg-hire-300 px-4 text-sm font-semibold text-ink-950 hover:bg-hire-200" onClick={saveDraft} type="button">保存变量</button>
          </div> : null}
          {view === "rename" && selectedVariable ? <div className="space-y-4 p-5"><label className="block text-xs font-semibold text-slate-300">新名称<input autoFocus className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-[#0b1220] px-3 font-mono text-sm text-white outline-none focus:border-brand-300/55" onChange={(event) => setRenameValue(event.target.value)} value={renameValue} /></label>{renamePlan?.blockers.length ? <div className="rounded-xl border border-rose-300/25 bg-rose-300/10 p-4"><p className="text-sm font-semibold text-rose-100">无法自动改名</p><ul className="mt-2 list-disc space-y-1 pl-4 text-xs leading-5 text-rose-100/85">{renamePlan.blockers.map((blocker) => <li key={blocker}>{blocker}</li>)}</ul></div> : <div className="rounded-xl border border-emerald-300/20 bg-emerald-300/5 p-4"><p className="text-sm font-semibold text-emerald-100">变更预览</p><p className="mt-2 text-xs leading-5 text-slate-300">将更新生产字段及 {renamePlan?.changes.length ?? 0} 个声明或引用位置，并作为一次撤销步骤。</p><div className="mt-3 max-h-48 space-y-1 overflow-y-auto">{renamePlan?.changes.map((change, index) => <p className="truncate text-[11px] text-slate-400" key={`${change.nodeId}-${change.field}-${index}`}>{change.nodeTitle} · {change.field}</p>)}</div></div>}<button className="min-h-11 w-full rounded-full bg-hire-300 px-4 text-sm font-semibold text-ink-950 hover:bg-hire-200 disabled:bg-white/10 disabled:text-slate-500" disabled={!renamePlan?.allowed || renamePlan.newName === selectedName} onClick={() => { if (!renamePlan?.allowed) return; onApplyRename(renamePlan); setSelectedName(renamePlan.newName); setView("detail"); }} type="button">确认改名</button></div> : null}
        </div>
      </aside>
    </div>, document.body,
  );
}
