"""Fixed, synthetic R8E video certification material.

Generated offline with the pinned ffmpeg container recorded in the R8E task
card.  The clip is one second of a blue square on a white background and
contains no user or remote content.
"""

from __future__ import annotations

import base64
import hashlib


SYNTHETIC_VIDEO_FIXTURE_ID = "r8e-blue-square-mp4-v1"
SYNTHETIC_VIDEO_MEDIA_TYPE = "video/mp4"
SYNTHETIC_VIDEO_WIDTH = 96
SYNTHETIC_VIDEO_HEIGHT = 64
SYNTHETIC_VIDEO_DURATION_MS = 1000
SYNTHETIC_VIDEO_MP4_SHA256 = (
    "cf085f8d5e5a66ace9dc6f2d259d530572865b790fb26c20708a6ed4eb5b4ecd"
)
_SYNTHETIC_VIDEO_MP4_BASE64 = (
    "AAAAJGZ0eXBpc29tAAACAGlzb21pc282aXNvMmF2YzFtcDQxAAAC521vb3YAAABsbXZoZAAAAAAAAAAAAAAAAAAA"
    "A+gAAAAAAAEAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAIAAAHqdHJhawAAAFx0a2hkAAAAAwAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAABgAAAAQAAAAAABhm1kaWEAAAAg"
    "bWRoZAAAAAAAAAAAAAAAAAAAKAAAAAAAVcQAAAAAAC1oZGxyAAAAAAAAAAB2aWRlAAAAAAAAAAAAAAAAVmlkZW9I"
    "YW5kbGVyAAAAATFtaW5mAAAAFHZtaGQAAAABAAAAAAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJs"
    "IAAAAAEAAADxc3RibAAAAKVzdHNkAAAAAAAAAAEAAACVYXZjMQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAABgAEAA"
    "SAAAAEgAAAAAAAAAARVMYXZjNjEuMTkuMTAwIGxpYngyNjQAAAAAAAAAAAAAABj//wAAAC9hdmNDAULAHv/hABdn"
    "QsAe2QYmwEQAAAMABAAAAwAoPFi5IAEABWjLg8sgAAAAEHBhc3AAAAABAAAAAQAAABBzdHRzAAAAAAAAAAAAAAAQ"
    "c3RzYwAAAAAAAAAAAAAAFHN0c3oAAAAAAAAAAAAAAAAAAAAQc3RjbwAAAAAAAAAAAAAAKG12ZXgAAAAgdHJleAAA"
    "AAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAGF1ZHRhAAAAWW1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBs"
    "AAAAAAAAAAAAAAAALGlsc3QAAAAkqXRvbwAAABxkYXRhAAAAAQAAAABMYXZmNjEuNy4xMDAAAACEbW9vZgAAABBt"
    "ZmhkAAAAAAAAAAEAAABsdHJhZgAAACR0ZmhkAAAAOQAAAAEAAAAAAAADCwAACAAAAAMGAQEAAAAAABR0ZmR0AQAA"
    "AAAAAAAAAAAAAAAALHRydW4AAAIFAAAABQAAAIwCAAAAAAADBgAAAAoAAAALAAAACgAAAAoAAAM3bWRhdAAAAmIG"
    "Bf//XtxF6b3m2Ui3lizYINkj7u94MjY0IC0gY29yZSAxNjQgLSBILjI2NC9NUEVHLTQgQVZDIGNvZGVjIC0gQ29w"
    "eWxlZnQgMjAwMy0yMDIzIC0gaHR0cDovL3d3dy52aWRlb2xhbi5vcmcveDI2NC5odG1sIC0gb3B0aW9uczogY2Fi"
    "YWM9MCByZWY9MyBkZWJsb2NrPTE6MDowIGFuYWx5c2U9MHgxOjB4MTExIG1lPWhleCBzdWJtZT03IHBzeT0xIHBz"
    "eV9yZD0xLjAwOjAuMDAgbWl4ZWRfcmVmPTEgbWVfcmFuZ2U9MTYgY2hyb21hX21lPTEgdHJlbGxpcz0xIDh4OGRj"
    "dD0wIGNxbT0wIGRlYWR6b25lPTIxLDExIGZhc3RfcHNraXA9MSBjaHJvbWFfcXBfb2Zmc2V0PS0yIHRocmVhZHM9"
    "MiBsb29rYWhlYWRfdGhyZWFkcz0xIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNpbWF0ZT0xIGludGVybGFjZWQ9"
    "MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTAgd2VpZ2h0cD0wIGtleWludD0y"
    "NTAga2V5aW50X21pbj01IHNjZW5lY3V0PTQwIGludHJhX3JlZnJlc2g9MCByY19sb29rYWhlYWQ9NDAgcmM9Y3Jm"
    "IG1idHJlZT0xIGNyZj0yMy4wIHFjb21wPTAuNjAgcXBtaW49MCBxcG1heD02OSBxcHN0ZXA9NCBpcF9yYXRpbz0x"
    "LjQwIGFxPTE6MS4wMACAAAAAnGWIhAR8mKAANSEnJycnJ//8OCwE3FAAEG2EATgChgFE4AoC7MCHnm2qWABABWIH"
    "UunhYFoy5v+hML8Q//YKjhACcAQMAgTAFQszgp5xtq8sABABGIHp9nAsVBPXX//8GCoEwQAmMcA/AFQs7gpxhtq4"
    "Ht8LRli/+BIL//7BUcIAmOcBuAKAu7Ahxptq/A612oJ665uMBjAbW1rrrwAAAAZBmjgI+GYAAAAHQZpUAj4ZgAAA"
    "AAZBmmAQ8MwAAAAGQZqAP8MwAAAAQ21mcmEAAAArdGZyYQEAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAML"
    "AQEBAAAAEG1mcm8AAAAAAAAAQw=="
)
SYNTHETIC_VIDEO_MP4_BYTES = base64.b64decode(
    _SYNTHETIC_VIDEO_MP4_BASE64,
    validate=True,
)
if (
    len(SYNTHETIC_VIDEO_MP4_BYTES) != 1801
    or SYNTHETIC_VIDEO_MP4_BYTES[4:8] != b"ftyp"
    or hashlib.sha256(SYNTHETIC_VIDEO_MP4_BYTES).hexdigest()
    != SYNTHETIC_VIDEO_MP4_SHA256
):
    raise RuntimeError("R8E synthetic video fixture failed its integrity check")
SYNTHETIC_VIDEO_MP4_DATA_URL = (
    f"data:{SYNTHETIC_VIDEO_MEDIA_TYPE};base64,{_SYNTHETIC_VIDEO_MP4_BASE64}"
)
