"""Generated non-executable manifests for the approved MCP catalog expansion."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class CatalogExpansionV2Adapter:
    project_id: str
    availability: str
    decision_reason_code: str
    adapter_version: str
    adaptation_wave: int
    connection_kind: str
    risk: str
    required_capabilities: tuple[str, ...]
    limitations: tuple[str, ...]


CATALOG_EXPANSION_V2_ADAPTERS = (
    CatalogExpansionV2Adapter(
        project_id='deusdata-codebase-memory-mcp',
        availability='blocked',
        decision_reason_code='blocked-superseded-code-index-implementation',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('代码索引批次只保留一个断网、封存仓库和临时索引实现；该候选依赖外部图数据库或为单语言宽工具面，不能在不扩大运行时的情况下优于已选固定 facade。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='0xmassi-webclaw',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-browser-or-url-surface',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游开放任意 URL、浏览器状态或反自动化能力，无法复用已冻结的匿名单 Origin 浏览器契约。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='co-browser-browser-use-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-browser-or-url-surface',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游开放任意 URL、浏览器状态或反自动化能力，无法复用已冻结的匿名单 Origin 浏览器契约。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='sipyourdrink-ltd-bernstein',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-command-or-code-execution',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('上游核心能力是任意命令、代码、容器或仓库写入，不能降格为固定只读工具而保持产品身份。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='beever-ai-beever-atlas',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adapter_version='',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('批次 21 暂缓实现；等待项目级持久卷、租户/项目所有权、容量与模型费用配额、保留/导出/删除生命周期、一次性写入审批和崩溃恢复语义完成后再复审。', '当前没有镜像、命令、端点、持久卷、模型配置、工具策略或功能开关绕过路径。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='googleapis-genai-toolbox',
        availability='blocked',
        decision_reason_code='blocked-dynamic-database-control-plane',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('上游通过动态工具配置连接多种数据库与云控制面，不能冻结为单一协议、只读账号和固定 Schema。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='flox-foundation-flox-mcp',
        availability='blocked',
        decision_reason_code='blocked-financial-or-transactional-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游包含订单、链上交易或真实资金相关操作；本目录不开放交易执行与签名能力。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='us-crw',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-host-or-target-surface',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游接受任意搜索实例、抓取目标、桌面宿主或本地服务；当前固定域名与受控上传边界不能证明目标归属。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='fatwang2-search1api-mcp',
        availability='ready',
        decision_reason_code='ready-official-native-discovery-only-facade',
        adapter_version='0.5.3-compatible-native-v1',
        adaptation_wave=15,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('encrypted-credential-binding', 'credential-revocation-check', 'fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('仅开放官方 v0.5.3 的 search、news 与 trending；crawl、sitemap、截图、结构化提取和任意页面抓取均关闭。', 'API Key 仅由服务端加密库注入，出口固定为 api.search1api.com；搜索与新闻强制 crawl_results=0，每次最多 20 条。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='markuspfundstein-mcp-obsidian',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-host-or-target-surface',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游接受任意搜索实例、抓取目标、桌面宿主或本地服务；当前固定域名与受控上传边界不能证明目标归属。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='mrexodia-ida-pro-mcp',
        availability='blocked',
        decision_reason_code='blocked-desktop-host-instance-unverified',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('上游依赖桌面应用插件或本机实例；当前没有可信宿主桥接、实例所有权证明和逐应用授权。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='qdrant-mcp-server-qdrant',
        availability='ready',
        decision_reason_code='ready-isolated-readonly-data-service-facade',
        adapter_version='0.8.1-compatible-native-read-only-v1',
        adaptation_wave=19,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('Qdrant MCP Server v0.8.1 的单 collection 只读 facade 已通过真实 Qdrant、原生只读 Key、Schema、代表查询、拒写与清理验收；qdrant-store 和任意过滤/管理入口保持关闭。', '仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='wonderwhy-er-desktopcommandermcp',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-command-or-code-execution',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('上游核心能力是任意命令、代码、容器或仓库写入，不能降格为固定只读工具而保持产品身份。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='blazickjp-arxiv-mcp-server',
        availability='ready',
        decision_reason_code='ready-native-read-only-metadata-facade',
        adapter_version='0.6.2-compatible-native-v1',
        adaptation_wave=14,
        connection_kind='sandboxed-stdio',
        risk='low',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('仅开放 v0.6.2 的 search_papers 与 get_abstract 元数据子集；每次最多 20 篇，并强制 3 秒请求间隔。', '出口固定为 export.arxiv.org；下载、全文读取、本地缓存、提醒、语义索引、引用导出和文件资源均关闭。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='goldentrii-agentrecall',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adapter_version='',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('批次 21 暂缓实现；等待项目级持久卷、租户/项目所有权、容量与模型费用配额、保留/导出/删除生命周期、一次性写入审批和崩溃恢复语义完成后再复审。', '当前没有镜像、命令、端点、持久卷、模型配置、工具策略或功能开关绕过路径。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='zcaceres-markdownify-mcp',
        availability='ready',
        decision_reason_code='ready-isolated-deterministic-file-artifact-facade',
        adapter_version='1.1.0-compatible-native-v1',
        adaptation_wave=18,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('Markdownify MCP v1.1.0 的四个本地文件转 Markdown 工具已通过断网、封存输入、确定性产物、超时与清理验收；网页、图片、音频、Git 和任意路径工具保持关闭。', '仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='benborla-mcp-server-mysql',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-capability',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('该实现与目录中已存在的受控文件或数据库能力重复，且没有更窄、更可验证的权限边界；不再新增重复运行时。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='samuelgursky-davinci-resolve-mcp',
        availability='blocked',
        decision_reason_code='blocked-desktop-host-instance-unverified',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('上游依赖桌面应用插件或本机实例；当前没有可信宿主桥接、实例所有权证明和逐应用授权。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='aas-ee-open-websearch',
        availability='ready',
        decision_reason_code='ready-native-fixed-engine-search-facade',
        adapter_version='2.1.9-compatible-native-v1',
        adaptation_wave=17,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('open-webSearch v2.1.9 的搜索契约已锁定；原生兼容层仅开放 Bing RSS 与 DuckDuckGo Strict SafeSearch 的固定请求模式，网页抓取、浏览器模式、代理、任意 URL/Header/环境变量和关闭证书校验均不可发现。', '仅允许匿名固定域名调用；命令、端点、Header、环境变量、凭据和上游写工具均不可发现。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='chigwell-telegram-mcp',
        availability='blocked',
        decision_reason_code='blocked-broad-account-or-message-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游覆盖外部账号、消息或协作对象的广泛读写；多租户 OAuth、最小 scope 和目标审批尚未完成。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='codergamester-mcp-unity',
        availability='blocked',
        decision_reason_code='blocked-desktop-host-instance-unverified',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('上游依赖桌面应用插件或本机实例；当前没有可信宿主桥接、实例所有权证明和逐应用授权。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='flux159-mcp-server-kubernetes',
        availability='blocked',
        decision_reason_code='blocked-privileged-infrastructure-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游可直接修改集群、云资源或 Terraform 状态；固定只读 facade 与强制审批尚不存在。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='genomoncology-biomcp',
        availability='ready',
        decision_reason_code='ready-native-anonymous-biomedical-metadata-facade',
        adapter_version='0.8.25-compatible-native-v1',
        adaptation_wave=16,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('BioMCP v0.8.25 的 search/get 契约已锁定；原生兼容层仅开放 Europe PMC、ClinicalTrials.gov 与 MyVariant.info 的匿名公共元数据，原始查询、研究文件与诊断上传关闭。', '仅允许匿名固定域名调用；命令、端点、Header、环境变量、凭据和上游写工具均不可发现。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='nickclyde-duckduckgo-mcp-server',
        availability='ready',
        decision_reason_code='ready-native-anonymous-search-facade',
        adapter_version='0.6.1-compatible-native-v1',
        adaptation_wave=16,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('DuckDuckGo MCP Server v0.6.1 的搜索契约已锁定；仅保留 Strict SafeSearch 搜索，网页抓取、任意 URL、Header、环境变量和关闭安全搜索均不可发现。', '仅允许匿名固定域名调用；命令、端点、Header、环境变量、凭据和上游写工具均不可发现。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='oraios-serena',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-command-or-code-execution',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('上游核心能力是任意命令、代码、容器或仓库写入，不能降格为固定只读工具而保持产品身份。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='taylorwilsdon-google-workspace-mcp',
        availability='blocked',
        decision_reason_code='blocked-broad-account-or-message-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游覆盖外部账号、消息或协作对象的广泛读写；多租户 OAuth、最小 scope 和目标审批尚未完成。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='mnemox-ai-idea-reality-mcp',
        availability='ready',
        decision_reason_code='ready-native-public-idea-research-facade',
        adapter_version='0.5.0-compatible-native-v1',
        adaptation_wave=17,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('Idea Reality MCP v0.5.0 的 idea_check 契约已锁定；仅查询 GitHub、Hacker News、npm 与 PyPI 公共索引，Product Hunt Token、LLM 调用、账号数据、诊断上传和任意端点均关闭。', '仅允许匿名固定域名调用；命令、端点、Header、环境变量、凭据和上游写工具均不可发现。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='chopratejas-headroom',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adapter_version='',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('批次 21 暂缓实现；等待项目级持久卷、租户/项目所有权、容量与模型费用配额、保留/导出/删除生命周期、一次性写入审批和崩溃恢复语义完成后再复审。', '当前没有镜像、命令、端点、持久卷、模型配置、工具策略或功能开关绕过路径。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='designcomputer-mysql-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-capability',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('该实现与目录中已存在的受控文件或数据库能力重复，且没有更窄、更可验证的权限边界；不再新增重复运行时。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='freepeak-db-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-capability',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('该实现与目录中已存在的受控文件或数据库能力重复，且没有更窄、更可验证的权限边界；不再新增重复运行时。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='ihor-sokoliuk-mcp-searxng',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-host-or-target-surface',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游接受任意搜索实例、抓取目标、桌面宿主或本地服务；当前固定域名与受控上传边界不能证明目标归属。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='inditextech-mcp-teams-server',
        availability='blocked',
        decision_reason_code='blocked-broad-account-or-message-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游覆盖外部账号、消息或协作对象的广泛读写；多租户 OAuth、最小 scope 和目标审批尚未完成。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='kagisearch-kagimcp',
        availability='ready',
        decision_reason_code='ready-official-native-read-only-api-facade',
        adapter_version='1.0.2-compatible-native-v1',
        adaptation_wave=14,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('encrypted-credential-binding', 'credential-revocation-check', 'fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery'),
        limitations=('仅开放官方 v1.0.2 的 kagi_search_fetch 与 kagi_extract；搜索结果上限降为 20，域名、Lens 和批量提取参数不开放。', 'Kagi API Key 仅由服务端加密库注入，出口固定为 kagi.com；提取 URL 必须为公网 HTTPS 且不能携带凭据型查询参数。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='mcpdotdirect-evm-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-financial-or-transactional-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游包含订单、链上交易或真实资金相关操作；本目录不开放交易执行与签名能力。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='shashankss1205-codegraphcontext',
        availability='blocked',
        decision_reason_code='blocked-superseded-code-index-implementation',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('代码索引批次只保留一个断网、封存仓库和临时索引实现；该候选依赖外部图数据库或为单语言宽工具面，不能在不扩大运行时的情况下优于已选固定 facade。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='tuanle96-mcp-odoo',
        availability='blocked',
        decision_reason_code='blocked-broad-account-or-message-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游覆盖外部账号、消息或协作对象的广泛读写；多租户 OAuth、最小 scope 和目标审批尚未完成。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='ckreiling-mcp-server-docker',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-command-or-code-execution',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('上游核心能力是任意命令、代码、容器或仓库写入，不能降格为固定只读工具而保持产品身份。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='coding-solo-godot-mcp',
        availability='blocked',
        decision_reason_code='blocked-desktop-host-instance-unverified',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('上游依赖桌面应用插件或本机实例；当前没有可信宿主桥接、实例所有权证明和逐应用授权。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='cyberchitta-llm-context-py',
        availability='ready',
        decision_reason_code='ready-isolated-file-analysis-facade',
        adapter_version='0.6.4-reviewed-commit-6de16c22-compatible-native-v1',
        adaptation_wave=18,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('llm-context 0.6.4 的封存工作区预览与 outline 产物已通过断网、Schema、双轮确定性、超时与清理验收；root_path、动态规则、剪贴板和项目写入保持关闭。', '仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='haris-musa-excel-mcp-server',
        availability='ready',
        decision_reason_code='ready-isolated-file-analysis-facade',
        adapter_version='0.1.8-compatible-native-v1',
        adaptation_wave=18,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('Excel MCP Server v0.1.8 的 XLSX 元数据、范围读取和确定性输出副本已通过断网、宏/外链/公式拒绝、源文件不可变、超时与清理验收；任意 filepath 和原地覆盖保持关闭。', '仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='idosal-git-mcp',
        availability='ready',
        decision_reason_code='ready-native-canonical-github-repository-facade',
        adapter_version='c487a298-compatible-native-v1',
        adaptation_wave=17,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('GitMCP 审阅提交 c487a298 的仓库文档与代码搜索能力已收窄为规范 GitHub owner/repository slug；仅访问 api.github.com，动态 MCP endpoint、任意 URL 抓取、Token、clone 与仓库写入均关闭。', '仅允许匿名固定域名调用；命令、端点、Header、环境变量、凭据和上游写工具均不可发现。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='nteract-semiotic',
        availability='blocked',
        decision_reason_code='blocked-not-an-executable-mcp-server',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('固定仓库未证明存在可锁定、可独立运行并可发现工具的 MCP Server 产品身份。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='public-ui-kolibri',
        availability='blocked',
        decision_reason_code='blocked-not-an-executable-mcp-server',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('固定仓库未证明存在可锁定、可独立运行并可发现工具的 MCP Server 产品身份。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='radareorg-radare2-mcp',
        availability='blocked',
        decision_reason_code='blocked-desktop-host-instance-unverified',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('上游依赖桌面应用插件或本机实例；当前没有可信宿主桥接、实例所有权证明和逐应用授权。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='skyhook-io-radar',
        availability='blocked',
        decision_reason_code='blocked-privileged-infrastructure-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('上游可直接修改集群、云资源或 Terraform 状态；固定只读 facade 与强制审批尚不存在。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='suekou-mcp-notion-server',
        availability='blocked',
        decision_reason_code='blocked-superseded-unbounded-third-party',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('该第三方实现提供的管理或写入面宽于目录中已存在的官方受控适配器，不再新增重复执行入口。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='xing5-mcp-google-sheets',
        availability='blocked',
        decision_reason_code='blocked-broad-account-or-message-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('上游覆盖外部账号、消息或协作对象的广泛读写；多租户 OAuth、最小 scope 和目标审批尚未完成。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='comet-ml-opik-mcp',
        availability='planned',
        decision_reason_code='planned-real-account-readonly-preflight-required',
        adapter_version='0.2.15-compatible-native-v1',
        adaptation_wave=17,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('Opik 0.2.15 的 list/read 兼容层、固定 Comet Cloud 出口与 Schema 已冻结；当前缺少真实 workspace 只读预检，因此继续保持 planned 且默认关闭。', '仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='quarkiverse-quarkus-mcp-servers-filesystem',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-capability',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('该实现与目录中已存在的受控文件或数据库能力重复，且没有更窄、更可验证的权限边界；不再新增重复运行时。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='quarkiverse-quarkus-mcp-servers-jdbc',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-capability',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('该实现与目录中已存在的受控文件或数据库能力重复，且没有更窄、更可验证的权限边界；不再新增重复运行时。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='samvallad33-vestige',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adapter_version='',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('批次 21 暂缓实现；等待项目级持久卷、租户/项目所有权、容量与模型费用配额、保留/导出/删除生命周期、一次性写入审批和崩溃恢复语义完成后再复审。', '当前没有镜像、命令、端点、持久卷、模型配置、工具策略或功能开关绕过路径。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='vivekvells-mcp-pandoc',
        availability='ready',
        decision_reason_code='ready-isolated-deterministic-file-artifact-facade',
        adapter_version='0.11.0-compatible-native-v1',
        adaptation_wave=18,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('MCP Pandoc v0.11.0 的 convert-contents 已通过固定 Pandoc 3.10.1、断网、封存输入、确定性产物、超时与清理验收；filter、template、PDF 与任意路径保持关闭。', '仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='yolfinance-yolfi-agent',
        availability='blocked',
        decision_reason_code='blocked-financial-or-transactional-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游包含订单、链上交易或真实资金相关操作；本目录不开放交易执行与签名能力。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='zilliztech-mcp-server-milvus',
        availability='planned',
        decision_reason_code='planned-read-only-data-facade',
        adapter_version='planned',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('保留为 planned；需要固定目标配置、原生只读账号、查询上限与逐工具 Schema 后才能接入。', '仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='alexei-led-k8s-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-privileged-infrastructure-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游可直接修改集群、云资源或 Terraform 状态；固定只读 facade 与强制审批尚不存在。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='anypost-emailmd',
        availability='blocked',
        decision_reason_code='blocked-publishing-or-high-risk-advice',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游涉及账号发布、邮件交付或高风险投资建议；当前不开放现实后果写入与可能诱导交易的运行时。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='brave-brave-search-mcp-server',
        availability='ready',
        decision_reason_code='ready-official-read-only-token-contract',
        adapter_version='2.1.0',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('encrypted-credential-binding', 'credential-revocation-check', 'fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery'),
        limitations=('仅开放官方 v2.1.0 的 brave_web_search 与 brave_local_search；其余搜索、摘要和媒体工具不可发现、不可调用。', 'Brave API Key 仅由服务端加密库注入，出口固定为 api.search.brave.com；不接受命令、端点、Header 或环境变量。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='cablate-mcp-google-map',
        availability='planned',
        decision_reason_code='planned-real-account-readonly-preflight-required',
        adapter_version='0.0.53-compatible-native-v1',
        adaptation_wave=17,
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('Google Maps v0.0.53 的 Places 只读兼容层、固定出口与 Schema 已冻结；当前缺少真实 API Key 代表调用，因此继续保持 planned 且默认关闭。', '仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='diivi-aseprite-mcp',
        availability='blocked',
        decision_reason_code='blocked-desktop-host-instance-unverified',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('上游依赖桌面应用插件或本机实例；当前没有可信宿主桥接、实例所有权证明和逐应用授权。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='docker-hub-mcp',
        availability='ready',
        decision_reason_code='ready-official-native-anonymous-metadata-facade',
        adapter_version='0.18.0-compatible-native-v1',
        adaptation_wave=16,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('官方 Docker Hub MCP v0.18.0 的匿名只读子集已锁定；仅开放仓库搜索、仓库元数据和标签元数据，账号、PAT、仓库写入、组织 DHI 和镜像执行均关闭。', '仅允许匿名固定域名调用；命令、端点、Header、环境变量、凭据和上游写工具均不可发现。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='integromat-make-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-broad-account-or-message-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游覆盖外部账号、消息或协作对象的广泛读写；多租户 OAuth、最小 scope 和目标审批尚未完成。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='ivanmurzak-unity-mcp',
        availability='blocked',
        decision_reason_code='blocked-desktop-host-instance-unverified',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('上游依赖桌面应用插件或本机实例；当前没有可信宿主桥接、实例所有权证明和逐应用授权。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='juyterman1000-entroly',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adapter_version='',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('批次 21 暂缓实现；等待项目级持久卷、租户/项目所有权、容量与模型费用配额、保留/导出/删除生命周期、一次性写入审批和崩溃恢复语义完成后再复审。', '当前没有镜像、命令、端点、持久卷、模型配置、工具策略或功能开关绕过路径。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='livetennisapi-livetennisapi-mcp',
        availability='ready',
        decision_reason_code='ready-official-native-free-read-only-facade',
        adapter_version='1.4.0-compatible-native-v1',
        adaptation_wave=15,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('encrypted-credential-binding', 'credential-revocation-check', 'fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('仅开放官方 v1.4.0 对应 FREE 层的实时/即将开始比赛、当前比分、球员、赛程与赛事目录；历史、赔率、市场、预测、模型分析、统计和 WebSocket 均关闭。', '响应按固定字段投影并移除 win_probability、danger、market、analysis 与 stats；API Key 仅由服务端加密库注入，出口固定为 api.livetennisapi.com。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='neo4j-contrib-mcp-neo4j',
        availability='planned',
        decision_reason_code='planned-read-only-data-facade',
        adapter_version='planned',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('保留为 planned；需要固定目标配置、原生只读账号、查询上限与逐工具 Schema 后才能接入。', '仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='pab1it0-prometheus-mcp-server',
        availability='ready',
        decision_reason_code='ready-isolated-readonly-data-service-facade',
        adapter_version='1.6.2-compatible-native-read-only-v1',
        adaptation_wave=19,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('Prometheus MCP Server v1.6.2 的固定只读 facade 已通过真实 Prometheus、Schema、PromQL/范围/结果上限、429、超时、拒写与清理验收；任意 URL/Header 和管理能力保持关闭。', '仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='pv-bhat-vibe-check-mcp-server',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adapter_version='',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('批次 21 暂缓实现；等待项目级持久卷、租户/项目所有权、容量与模型费用配额、保留/导出/删除生命周期、一次性写入审批和崩溃恢复语义完成后再复审。', '当前没有镜像、命令、端点、持久卷、模型配置、工具策略或功能开关绕过路径。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='r-huijts-strava-mcp',
        availability='planned',
        decision_reason_code='planned-wave22-multitenant-oauth-foundation-required',
        adapter_version='',
        adaptation_wave=22,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'oauth-pkce-refresh-revocation', 'fixed-read-only-scope'),
        limitations=('批次 22 暂缓实现；等待不可伪造的逐请求主体、租户隔离、OAuth 2.1 PKCE/state、最小只读 Scope、刷新/撤销/解绑和账号资源所有权证明完成后再复审。', '当前没有 OAuth 回调、客户端密钥、Token 存储、命令、端点、工具策略或功能开关绕过路径。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='runekaagaard-mcp-alchemy',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-capability',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('该实现与目录中已存在的受控文件或数据库能力重复，且没有更窄、更可验证的权限边界；不再新增重复运行时。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='safedep-vet',
        availability='ready',
        decision_reason_code='ready-native-anonymous-package-insight-facade',
        adapter_version='1.18.1-compatible-native-v1',
        adaptation_wave=16,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('SafeDep Vet v1.18.1 的六个包洞察工具已锁定；原生兼容层仅接受规范化 npm/PyPI PURL，查询社区洞察及公共 Registry 元数据，不下载、不执行、不上传包。', '仅允许匿名固定域名调用；命令、端点、Header、环境变量、凭据和上游写工具均不可发现。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='stack-chan-stack-chan',
        availability='blocked',
        decision_reason_code='blocked-physical-device-control',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('上游可控制机器人或物理设备；当前没有设备身份、急停、权限和现场安全边界。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='tacticlaunch-mcp-linear',
        availability='planned',
        decision_reason_code='planned-wave22-multitenant-oauth-foundation-required',
        adapter_version='',
        adaptation_wave=22,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'oauth-pkce-refresh-revocation', 'fixed-read-only-scope'),
        limitations=('批次 22 暂缓实现；等待不可伪造的逐请求主体、租户隔离、OAuth 2.1 PKCE/state、最小只读 Scope、刷新/撤销/解绑和账号资源所有权证明完成后再复审。', '当前没有 OAuth 回调、客户端密钥、Token 存储、命令、端点、工具策略或功能开关绕过路径。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='tiberriver256-mcp-server-azure-devops',
        availability='planned',
        decision_reason_code='planned-wave22-multitenant-oauth-foundation-required',
        adapter_version='',
        adaptation_wave=22,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'oauth-pkce-refresh-revocation', 'fixed-read-only-scope'),
        limitations=('批次 22 暂缓实现；等待不可伪造的逐请求主体、租户隔离、OAuth 2.1 PKCE/state、最小只读 Scope、刷新/撤销/解绑和账号资源所有权证明完成后再复审。', '当前没有 OAuth 回调、客户端密钥、Token 存储、命令、端点、工具策略或功能开关绕过路径。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='xquik-dev-x-twitter-scraper',
        availability='blocked',
        decision_reason_code='blocked-social-publishing-or-session-reuse',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游依赖社交账号发布、已登录会话或平台写入；不满足无登录态复用与逐次写审批边界。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='alexei-led-aws-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-privileged-infrastructure-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游可直接修改集群、云资源或 Terraform 状态；固定只读 facade 与强制审批尚不存在。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='arcadedata-arcadedb',
        availability='planned',
        decision_reason_code='planned-read-only-data-facade',
        adapter_version='planned',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('保留为 planned；需要固定目标配置、原生只读账号、查询上限与逐工具 Schema 后才能接入。', '仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='carterlasalle-mac-messages-mcp',
        availability='blocked',
        decision_reason_code='blocked-desktop-host-instance-unverified',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('上游依赖桌面应用插件或本机实例；当前没有可信宿主桥接、实例所有权证明和逐应用授权。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='cr7258-elasticsearch-mcp-server',
        availability='ready',
        decision_reason_code='ready-isolated-readonly-data-service-facade',
        adapter_version='2.1.2-compatible-native-read-only-v1',
        adaptation_wave=19,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('Elasticsearch MCP Server v2.1.2 的单 index/search field 只读 facade 已通过真实 Elasticsearch、原生只读角色、Schema、代表查询、拒写与清理验收；通用 API、写入和管理工具保持关闭。', '仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='datalayer-jupyter-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-command-or-code-execution',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('上游核心能力是任意命令、代码、容器或仓库写入，不能降格为固定只读工具而保持产品身份。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='emiliaprotocol-emilia-protocol',
        availability='blocked',
        decision_reason_code='blocked-not-an-executable-mcp-server',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('ephemeral-code-sandbox', 'scoped-filesystem', 'terminal-action-approval'),
        limitations=('固定仓库未证明存在可锁定、可独立运行并可发现工具的 MCP Server 产品身份。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='eyalzh-browser-control-mcp',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-browser-or-url-surface',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游开放任意 URL、浏览器状态或反自动化能力，无法复用已冻结的匿名单 Origin 浏览器契约。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='ferdousbhai-investor-agent',
        availability='blocked',
        decision_reason_code='blocked-publishing-or-high-risk-advice',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游涉及账号发布、邮件交付或高风险投资建议；当前不开放现实后果写入与可能诱导交易的运行时。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='jpisnice-shadcn-ui-mcp-server',
        availability='ready',
        decision_reason_code='ready-native-pinned-component-metadata-facade',
        adapter_version='2.0.0-compatible-native-v1',
        adaptation_wave=16,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('shadcn/ui MCP Server v2.0.0 的组件目录契约已锁定；仅列出固定提交中的组件并读取 Git 元数据，源码、Block、主题、本地写入和 GitHub Token 均关闭。', '仅允许匿名固定域名调用；命令、端点、Header、环境变量、凭据和上游写工具均不可发现。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='kiliczsh-mcp-mongo-server',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-capability',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('该实现与目录中已存在的受控文件或数据库能力重复，且没有更窄、更可验证的权限边界；不再新增重复运行时。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='lpigeon-ros-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-physical-device-control',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('上游可控制机器人或物理设备；当前没有设备身份、急停、权限和现场安全边界。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='nwiizo-tfmcp',
        availability='blocked',
        decision_reason_code='blocked-privileged-infrastructure-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游可直接修改集群、云资源或 Terraform 状态；固定只读 facade 与强制审批尚不存在。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='vectorize-io-vectorize-mcp-server',
        availability='planned',
        decision_reason_code='planned-real-account-readonly-preflight-required',
        adapter_version='0.4.3-compatible-native-v1',
        adaptation_wave=17,
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('Vectorize 0.4.3 的既有 pipeline 检索兼容层、固定出口与 Schema 已冻结；当前缺少真实组织、pipeline 与 Token 代表调用，且标签 LICENSE 与 package metadata 的许可证声明不一致，因此继续保持 planned 且默认关闭。', '仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='antvis-mcp-server-chart',
        availability='ready',
        decision_reason_code='ready-isolated-deterministic-file-artifact-facade',
        adapter_version='0.9.10-compatible-native-v1',
        adaptation_wave=18,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('AntV MCP Server Chart 0.9.10 的 line/bar/pie 工具已通过断网确定性 PNG、Schema、超时与清理验收；远程服务、地图、动态图表、任意端点和远程 URL 保持关闭。', '仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='caol64-wenyan-mcp',
        availability='blocked',
        decision_reason_code='blocked-social-publishing-or-session-reuse',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游依赖社交账号发布、已登录会话或平台写入；不满足无登录态复用与逐次写审批边界。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='dataeval-dingo',
        availability='ready',
        decision_reason_code='ready-isolated-file-analysis-facade',
        adapter_version='2.5.0-rule-compatible-native-v1',
        adaptation_wave=18,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('Dingo v2.5.0 的三个固定本地规则已通过断网、固定格式、Schema、双轮确定性、超时与清理验收；LLM、Agent、云数据源和动态 kwargs 保持关闭。', '仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='g0t4-mcp-server-commands',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-command-or-code-execution',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('上游核心能力是任意命令、代码、容器或仓库写入，不能降格为固定只读工具而保持产品身份。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='keboola-keboola-mcp-server',
        availability='planned',
        decision_reason_code='planned-real-account-readonly-preflight-required',
        adapter_version='1.75.2-compatible-native-v1',
        adaptation_wave=17,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('Keboola MCP v1.75.2 的项目与 Storage 元数据兼容层、固定美国栈出口与 Schema 已冻结；当前缺少真实只读 Storage Token 预检，因此继续保持 planned 且默认关闭。', '仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='line-line-bot-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-broad-account-or-message-write',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游覆盖外部账号、消息或协作对象的广泛读写；多租户 OAuth、最小 scope 和目标审批尚未完成。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='ozgurcd-gograph',
        availability='ready',
        decision_reason_code='ready-isolated-code-index-facade',
        adapter_version='1.5.6-reviewed-commit-aa4d6d54-compatible-native-v1',
        adaptation_wave=20,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('scoped-filesystem', 'ephemeral-code-index', 'resource-limits', 'one-shot-write-approval'),
        limitations=('GoGraph v1.5.6 的封存 Go 仓库一次性内存索引与六个固定结构读取工具已通过真实断网镜像、双轮 UDS、Schema、超时、源不可变和清理验收；网络、持久化、任意路径、Git 基线、边界配置、会话遥测、Wiki 与 doc 工具保持关闭。', '只允许封存 Go 工作区、固定二进制、六工具 Schema、断网和一次性内存索引；默认文件 sidecar allowlist 只增加该精确 ID。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='patdolitse-piia-engram',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adapter_version='',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('批次 21 暂缓实现；等待项目级持久卷、租户/项目所有权、容量与模型费用配额、保留/导出/删除生命周期、一次性写入审批和崩溃恢复语义完成后再复审。', '当前没有镜像、命令、端点、持久卷、模型配置、工具策略或功能开关绕过路径。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='taisly-agent',
        availability='blocked',
        decision_reason_code='blocked-social-publishing-or-session-reuse',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('上游依赖社交账号发布、已登录会话或平台写入；不满足无登录态复用与逐次写审批边界。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='zinja-coder-jadx-ai-mcp',
        availability='blocked',
        decision_reason_code='blocked-desktop-host-instance-unverified',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('上游依赖桌面应用插件或本机实例；当前没有可信宿主桥接、实例所有权证明和逐应用授权。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='alexander-zuev-supabase-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-superseded-unbounded-third-party',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('该第三方实现提供的管理或写入面宽于目录中已存在的官方受控适配器，不再新增重复执行入口。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='bx33661-wireshark-mcp',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-host-or-target-surface',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('上游接受任意搜索实例、抓取目标、桌面宿主或本地服务；当前固定域名与受控上传边界不能证明目标归属。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='bytedance-ui-tars-desktop-browser',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-browser-or-url-surface',
        adapter_version='blocked',
        adaptation_wave=13,
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('上游开放任意 URL、浏览器状态或反自动化能力，无法复用已冻结的匿名单 Origin 浏览器契约。', '该条目保持不可执行；没有命令、端点、凭据槽、工具策略或连接入口，功能开关不能绕过。'),
    ),
)

CATALOG_EXPANSION_V2_IDS = tuple(
    item.project_id for item in CATALOG_EXPANSION_V2_ADAPTERS
)
