"""Generated classifications for the approved Wave 24 expansion."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class CatalogExpansionV3Adapter:
    project_id: str
    availability: str
    decision_reason_code: str
    adaptation_wave: int
    connection_kind: str
    risk: str
    required_capabilities: tuple[str, ...]
    limitations: tuple[str, ...]


CATALOG_EXPANSION_V3_ADAPTERS = (
    CatalogExpansionV3Adapter(
        project_id='yepcode-mcp-server-js',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-command-code-or-target',
        adaptation_wave=24,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('ephemeral-code-sandbox', 'terminal-action-approval'),
        limitations=('上游产品身份依赖任意命令、代码、包、仓库或网络目标；收窄后无法保持产品身份，因此不接入通用执行器并保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='ergut-mcp-bigquery-server',
        availability='planned',
        decision_reason_code='planned-wave26-token-readonly-preflight',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('encrypted-credential-binding', 'fixed-egress-policy', 'read-only-tool-policy', 'real-account-readonly-preflight'),
        limitations=('可继续评估固定凭据槽与账号资源作用域内的只读子集；在服务端加密凭据、固定出口、真实只读账号预检和代表调用完成前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='executeautomation-mcp-playwright',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-controlled-capability',
        adaptation_wave=24,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'bounded-runtime-surface'),
        limitations=('该实现与已存在的受控浏览器、搜索、文件或代码索引能力重复，且不会提供更窄、更可验证的边界；转为 blocked/superseded，不创建第二套运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='fradser-mcp-server-apple-reminders',
        availability='blocked',
        decision_reason_code='blocked-desktop-browser-or-device-control',
        adaptation_wave=24,
        connection_kind='desktop-bridge',
        risk='high',
        required_capabilities=('trusted-desktop-host', 'per-user-process-isolation'),
        limitations=('上游依赖桌面宿主、浏览器自动化、IDE/模拟器、设备控制或任意宿主路径；这些能力在多租户桌面宿主边界完成前继续冻结。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='githejie-mcp-server-calculator',
        availability='ready',
        decision_reason_code='ready-wave26a-calculator',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('network-disabled', 'bounded-runtime-surface', 'schema-drift-recovery', 'resource-limits'),
        limitations=('已冻结单一 calculate 工具、断网数值 AST、复杂度与结果上限，并通过真实 UDS、超时回收、默认拒绝和用户验收。',),
    ),
    CatalogExpansionV3Adapter(
        project_id='modelscope-funasr',
        availability='planned',
        decision_reason_code='planned-wave26-offline-file-or-deterministic-artifact',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('scoped-filesystem', 'network-disabled', 'artifact-cleanup', 'resource-limits'),
        limitations=('可继续评估断网、封存输入、确定性处理与服务端复制产物的文件子集；在路径隔离、资源限额、超时、清理和真实镜像验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='muvon-octocode',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-controlled-capability',
        adaptation_wave=24,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'bounded-runtime-surface'),
        limitations=('该实现与已存在的受控浏览器、搜索、文件或代码索引能力重复，且不会提供更窄、更可验证的边界；转为 blocked/superseded，不创建第二套运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='narumiruna-yfinance-mcp',
        availability='planned',
        decision_reason_code='planned-wave25-anonymous-public-read-contract',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('可继续评估匿名固定域名的公开搜索或元数据读取；在冻结上游版本、固定 Host、只读工具 Schema、限流与输出上限并完成真实代表调用前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='pspdfkit-nutrient-dws-mcp-server',
        availability='planned',
        decision_reason_code='planned-wave26-token-readonly-preflight',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('encrypted-credential-binding', 'fixed-egress-policy', 'read-only-tool-policy', 'real-account-readonly-preflight'),
        limitations=('可继续评估固定凭据槽与账号资源作用域内的只读子集；在服务端加密凭据、固定出口、真实只读账号预检和代表调用完成前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='rohitg00-kubectl-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='supermemoryai-supermemory',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('该产品依赖项目级持久化、保留/导出/删除、容量或模型费用配额及一次性写审批；Wave 21 基础完成前保持 planned，当前不创建运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='takashiishida-arxiv-latex-mcp',
        availability='planned',
        decision_reason_code='planned-wave25-anonymous-public-read-contract',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('可继续评估匿名固定域名的公开搜索或元数据读取；在冻结上游版本、固定 Host、只读工具 Schema、限流与输出上限并完成真实代表调用前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='tumf-mcp-shell-server',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-command-code-or-target',
        adaptation_wave=24,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('ephemeral-code-sandbox', 'terminal-action-approval'),
        limitations=('上游产品身份依赖任意命令、代码、包、仓库或网络目标；收窄后无法保持产品身份，因此不接入通用执行器并保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='zcaceres-fetch-mcp',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-command-code-or-target',
        adaptation_wave=24,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('ephemeral-code-sandbox', 'terminal-action-approval'),
        limitations=('上游产品身份依赖任意命令、代码、包、仓库或网络目标；收窄后无法保持产品身份，因此不接入通用执行器并保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='zcaceres-gtasks-mcp',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='chanmeng666-server-google-news',
        availability='planned',
        decision_reason_code='planned-wave26-token-readonly-preflight',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('encrypted-credential-binding', 'fixed-egress-policy', 'read-only-tool-policy', 'real-account-readonly-preflight'),
        limitations=('可继续评估固定凭据槽与账号资源作用域内的只读子集；在服务端加密凭据、固定出口、真实只读账号预检和代表调用完成前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='coinpaprika-dexpaprika-mcp',
        availability='ready',
        decision_reason_code='ready-wave25-public-read',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('已冻结上游版本、许可证、固定公共 Host、只读工具 Schema、限流和输出上限，并通过真实代表调用、拒写、超时、重启、清理与用户验收。',),
    ),
    CatalogExpansionV3Adapter(
        project_id='nkapila6-mcp-local-rag',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('该产品依赖项目级持久化、保留/导出/删除、容量或模型费用配额及一次性写审批；Wave 21 基础完成前保持 planned，当前不创建运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='secretiveshell-mcp-searxng',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-controlled-capability',
        adaptation_wave=24,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'bounded-runtime-surface'),
        limitations=('该实现与已存在的受控浏览器、搜索、文件或代码索引能力重复，且不会提供更窄、更可验证的边界；转为 blocked/superseded，不创建第二套运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='weibaohui-k8m',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='zenml-io-mcp-zenml',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='anaisbetts-mcp-youtube',
        availability='planned',
        decision_reason_code='planned-wave25-anonymous-public-read-contract',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('可继续评估匿名固定域名的公开搜索或元数据读取；在冻结上游版本、固定 Host、只读工具 Schema、限流与输出上限并完成真实代表调用前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='apinetwork-piapi-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-paid-generation-transaction-or-wallet',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('billing-guard', 'transaction-approval', 'unknown-outcome-recovery'),
        limitations=('上游核心能力会触发付费生成、账号余额、交易、钱包或外部模型执行；该类高后果副作用不纳入本阶段适配。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='apollographql-apollo-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='greptimeteam-greptimedb-mcp-server',
        availability='planned',
        decision_reason_code='planned-wave27-native-readonly-data-service',
        adaptation_wave=27,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('fixed-database-target', 'native-read-only-role', 'read-only-query-policy', 'query-and-output-limits'),
        limitations=('可继续评估固定协议、结构化目标和原生只读账号下的 describe/list/search/read-query 子集；DSN、管理操作、写查询和动态端点保持禁止，真实服务验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='joshuayoes-ios-simulator-mcp',
        availability='blocked',
        decision_reason_code='blocked-desktop-browser-or-device-control',
        adaptation_wave=24,
        connection_kind='desktop-bridge',
        risk='high',
        required_capabilities=('trusted-desktop-host', 'per-user-process-isolation'),
        limitations=('上游依赖桌面宿主、浏览器自动化、IDE/模拟器、设备控制或任意宿主路径；这些能力在多租户桌面宿主边界完成前继续冻结。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='utensils-mcp-nixos',
        availability='blocked',
        decision_reason_code='blocked-wave25-public-backend-requires-embedded-credential',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('provider-supported-anonymous-api', 'credential-provenance-review'),
        limitations=('固定 mcp-nixos v3.0.0 的核心 NixOS 搜索后端对匿名访问返回 401，上游源码内置了 Basic Auth 凭据。本批不复制这些值、不新增凭据槽、不更换后端冒充原产品，因此转为 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='callstackincubator-agent-device',
        availability='blocked',
        decision_reason_code='blocked-desktop-browser-or-device-control',
        adaptation_wave=24,
        connection_kind='desktop-bridge',
        risk='high',
        required_capabilities=('trusted-desktop-host', 'per-user-process-isolation'),
        limitations=('上游依赖桌面宿主、浏览器自动化、IDE/模拟器、设备控制或任意宿主路径；这些能力在多租户桌面宿主边界完成前继续冻结。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='dbt-labs-dbt-mcp',
        availability='planned',
        decision_reason_code='planned-wave27-native-readonly-data-service',
        adaptation_wave=27,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('fixed-database-target', 'native-read-only-role', 'read-only-query-policy', 'query-and-output-limits'),
        limitations=('可继续评估固定协议、结构化目标和原生只读账号下的 describe/list/search/read-query 子集；DSN、管理操作、写查询和动态端点保持禁止，真实服务验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='eat-pray-ai-yutu',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='flytohub-flyto-core',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-command-code-or-target',
        adaptation_wave=24,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('ephemeral-code-sandbox', 'terminal-action-approval'),
        limitations=('上游产品身份依赖任意命令、代码、包、仓库或网络目标；收窄后无法保持产品身份，因此不接入通用执行器并保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='freema-openclaw-mcp',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='higangssh-homebutler',
        availability='blocked',
        decision_reason_code='blocked-desktop-browser-or-device-control',
        adaptation_wave=24,
        connection_kind='desktop-bridge',
        risk='high',
        required_capabilities=('trusted-desktop-host', 'per-user-process-isolation'),
        limitations=('上游依赖桌面宿主、浏览器自动化、IDE/模拟器、设备控制或任意宿主路径；这些能力在多租户桌面宿主边界完成前继续冻结。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='jau123-meigen-ai-design-mcp',
        availability='blocked',
        decision_reason_code='blocked-paid-generation-transaction-or-wallet',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('billing-guard', 'transaction-approval', 'unknown-outcome-recovery'),
        limitations=('上游核心能力会触发付费生成、账号余额、交易、钱包或外部模型执行；该类高后果副作用不纳入本阶段适配。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='klavis-ai-klavis',
        availability='blocked',
        decision_reason_code='blocked-dynamic-integration-or-security-control-plane',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-control-plane', 'tenant-isolation', 'bounded-runtime-surface'),
        limitations=('上游是动态集成/安全控制面，工具、目标或运行服务会随外部配置扩张；无法冻结为固定产品契约，保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='korotovsky-slack-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='mckinsey-vizro',
        availability='planned',
        decision_reason_code='planned-wave26-offline-file-or-deterministic-artifact',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('scoped-filesystem', 'network-disabled', 'artifact-cleanup', 'resource-limits'),
        limitations=('可继续评估断网、封存输入、确定性处理与服务端复制产物的文件子集；在路径隔离、资源限额、超时、清理和真实镜像验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='mobilereality-mdma',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='planetscale-cli',
        availability='planned',
        decision_reason_code='planned-wave27-native-readonly-data-service',
        adaptation_wave=27,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('fixed-database-target', 'native-read-only-role', 'read-only-query-policy', 'query-and-output-limits'),
        limitations=('可继续评估固定协议、结构化目标和原生只读账号下的 describe/list/search/read-query 子集；DSN、管理操作、写查询和动态端点保持禁止，真实服务验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='pydantic-pydantic-ai',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-command-code-or-target',
        adaptation_wave=24,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('ephemeral-code-sandbox', 'terminal-action-approval'),
        limitations=('上游产品身份依赖任意命令、代码、包、仓库或网络目标；收窄后无法保持产品身份，因此不接入通用执行器并保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='repowise-dev-repowise',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-controlled-capability',
        adaptation_wave=24,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'bounded-runtime-surface'),
        limitations=('该实现与已存在的受控浏览器、搜索、文件或代码索引能力重复，且不会提供更窄、更可验证的边界；转为 blocked/superseded，不创建第二套运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='runapi-ai-mcp',
        availability='blocked',
        decision_reason_code='blocked-paid-generation-transaction-or-wallet',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('billing-guard', 'transaction-approval', 'unknown-outcome-recovery'),
        limitations=('上游核心能力会触发付费生成、账号余额、交易、钱包或外部模型执行；该类高后果副作用不纳入本阶段适配。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='anki-mcp-anki-mcp-desktop',
        availability='blocked',
        decision_reason_code='blocked-desktop-browser-or-device-control',
        adaptation_wave=24,
        connection_kind='desktop-bridge',
        risk='high',
        required_capabilities=('trusted-desktop-host', 'per-user-process-isolation'),
        limitations=('上游依赖桌面宿主、浏览器自动化、IDE/模拟器、设备控制或任意宿主路径；这些能力在多租户桌面宿主边界完成前继续冻结。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='bgauryy-octocode-mcp',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-controlled-capability',
        adaptation_wave=24,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'bounded-runtime-surface'),
        limitations=('该实现与已存在的受控浏览器、搜索、文件或代码索引能力重复，且不会提供更窄、更可验证的边界；转为 blocked/superseded，不创建第二套运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='childrentime-reactuse',
        availability='planned',
        decision_reason_code='planned-wave25-anonymous-public-read-contract',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('可继续评估匿名固定域名的公开搜索或元数据读取；在冻结上游版本、固定 Host、只读工具 Schema、限流与输出上限并完成真实代表调用前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='lvcidpsyche-auto-browser',
        availability='blocked',
        decision_reason_code='blocked-desktop-browser-or-device-control',
        adaptation_wave=24,
        connection_kind='desktop-bridge',
        risk='high',
        required_capabilities=('trusted-desktop-host', 'per-user-process-isolation'),
        limitations=('上游依赖桌面宿主、浏览器自动化、IDE/模拟器、设备控制或任意宿主路径；这些能力在多租户桌面宿主边界完成前继续冻结。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='openfate-ai-bazi-mcp',
        availability='planned',
        decision_reason_code='planned-wave26-offline-file-or-deterministic-artifact',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('scoped-filesystem', 'network-disabled', 'artifact-cleanup', 'resource-limits'),
        limitations=('可继续评估断网、封存输入、确定性处理与服务端复制产物的文件子集；在路径隔离、资源限额、超时、清理和真实镜像验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='polygon-io-mcp-polygon',
        availability='planned',
        decision_reason_code='planned-wave26-token-readonly-preflight',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('encrypted-credential-binding', 'fixed-egress-policy', 'read-only-tool-policy', 'real-account-readonly-preflight'),
        limitations=('可继续评估固定凭据槽与账号资源作用域内的只读子集；在服务端加密凭据、固定出口、真实只读账号预检和代表调用完成前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='scottcjn-rustchain-mcp',
        availability='blocked',
        decision_reason_code='blocked-paid-generation-transaction-or-wallet',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('billing-guard', 'transaction-approval', 'unknown-outcome-recovery'),
        limitations=('上游核心能力会触发付费生成、账号余额、交易、钱包或外部模型执行；该类高后果副作用不纳入本阶段适配。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='tonnode-mcp',
        availability='planned',
        decision_reason_code='planned-wave25-anonymous-public-read-contract',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('可继续评估匿名固定域名的公开搜索或元数据读取；在冻结上游版本、固定 Host、只读工具 Schema、限流与输出上限并完成真实代表调用前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='writerslogic-scrivener-mcp',
        availability='blocked',
        decision_reason_code='blocked-desktop-browser-or-device-control',
        adaptation_wave=24,
        connection_kind='desktop-bridge',
        risk='high',
        required_capabilities=('trusted-desktop-host', 'per-user-process-isolation'),
        limitations=('上游依赖桌面宿主、浏览器自动化、IDE/模拟器、设备控制或任意宿主路径；这些能力在多租户桌面宿主边界完成前继续冻结。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='gomarble-ai-facebook-ads-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='healthchainai-healthchain',
        availability='planned',
        decision_reason_code='planned-wave26-offline-file-or-deterministic-artifact',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('scoped-filesystem', 'network-disabled', 'artifact-cleanup', 'resource-limits'),
        limitations=('可继续评估断网、封存输入、确定性处理与服务端复制产物的文件子集；在路径隔离、资源限额、超时、清理和真实镜像验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='isnow890-naver-search-mcp',
        availability='planned',
        decision_reason_code='planned-wave26-token-readonly-preflight',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('encrypted-credential-binding', 'fixed-egress-policy', 'read-only-tool-policy', 'real-account-readonly-preflight'),
        limitations=('可继续评估固定凭据槽与账号资源作用域内的只读子集；在服务端加密凭据、固定出口、真实只读账号预检和代表调用完成前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='karanb192-reddit-mcp-buddy',
        availability='planned',
        decision_reason_code='planned-wave25-anonymous-public-read-contract',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('可继续评估匿名固定域名的公开搜索或元数据读取；在冻结上游版本、固定 Host、只读工具 Schema、限流与输出上限并完成真实代表调用前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='kunwar-shah-claudex',
        availability='blocked',
        decision_reason_code='blocked-desktop-browser-or-device-control',
        adaptation_wave=24,
        connection_kind='desktop-bridge',
        risk='high',
        required_capabilities=('trusted-desktop-host', 'per-user-process-isolation'),
        limitations=('上游依赖桌面宿主、浏览器自动化、IDE/模拟器、设备控制或任意宿主路径；这些能力在多租户桌面宿主边界完成前继续冻结。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='kzino-vorim-mcp-server',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('该产品依赖项目级持久化、保留/导出/删除、容量或模型费用配额及一次性写审批；Wave 21 基础完成前保持 planned，当前不创建运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='mariocandela-beelzebub',
        availability='blocked',
        decision_reason_code='blocked-dynamic-integration-or-security-control-plane',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-control-plane', 'tenant-isolation', 'bounded-runtime-surface'),
        limitations=('上游是动态集成/安全控制面，工具、目标或运行服务会随外部配置扩张；无法冻结为固定产品契约，保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='nameetp-pdfmux',
        availability='planned',
        decision_reason_code='planned-wave26-offline-file-or-deterministic-artifact',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('scoped-filesystem', 'network-disabled', 'artifact-cleanup', 'resource-limits'),
        limitations=('可继续评估断网、封存输入、确定性处理与服务端复制产物的文件子集；在路径隔离、资源限额、超时、清理和真实镜像验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='openaccountants-openaccountants',
        availability='planned',
        decision_reason_code='planned-wave25-anonymous-public-read-contract',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('可继续评估匿名固定域名的公开搜索或元数据读取；在冻结上游版本、固定 Host、只读工具 Schema、限流与输出上限并完成真实代表调用前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='pab1it0-chess-mcp',
        availability='ready',
        decision_reason_code='ready-wave25-public-read',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('已冻结上游版本、许可证、固定公共 Host、只读工具 Schema、限流和输出上限，并通过真实代表调用、拒写、超时、重启、清理与用户验收。',),
    ),
    CatalogExpansionV3Adapter(
        project_id='rashidazarang-airtable-mcp',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='rishijatia-fantasy-pl-mcp',
        availability='ready',
        decision_reason_code='ready-wave25-public-read',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('已冻结上游版本、许可证、固定公共 Host、只读工具 Schema、限流和输出上限，并通过真实代表调用、拒写、超时、重启、清理与用户验收。',),
    ),
    CatalogExpansionV3Adapter(
        project_id='rusiaaman-wcgw',
        availability='blocked',
        decision_reason_code='blocked-arbitrary-command-code-or-target',
        adaptation_wave=24,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('ephemeral-code-sandbox', 'terminal-action-approval'),
        limitations=('上游产品身份依赖任意命令、代码、包、仓库或网络目标；收窄后无法保持产品身份，因此不接入通用执行器并保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='snowflake-labs-mcp',
        availability='planned',
        decision_reason_code='planned-wave27-native-readonly-data-service',
        adaptation_wave=27,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('fixed-database-target', 'native-read-only-role', 'read-only-query-policy', 'query-and-output-limits'),
        limitations=('可继续评估固定协议、结构化目标和原生只读账号下的 describe/list/search/read-query 子集；DSN、管理操作、写查询和动态端点保持禁止，真实服务验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='stabgan-openrouter-mcp-multimodal',
        availability='blocked',
        decision_reason_code='blocked-paid-generation-transaction-or-wallet',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('billing-guard', 'transaction-approval', 'unknown-outcome-recovery'),
        limitations=('上游核心能力会触发付费生成、账号余额、交易、钱包或外部模型执行；该类高后果副作用不纳入本阶段适配。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='sunriseapps-imagesorcery-mcp',
        availability='planned',
        decision_reason_code='planned-wave26-offline-file-or-deterministic-artifact',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('scoped-filesystem', 'network-disabled', 'artifact-cleanup', 'resource-limits'),
        limitations=('可继续评估断网、封存输入、确定性处理与服务端复制产物的文件子集；在路径隔离、资源限额、超时、清理和真实镜像验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='xeroapi-xero-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='yuna0x0-anilist-mcp',
        availability='ready',
        decision_reason_code='ready-wave25-public-read',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('已冻结上游版本、许可证、固定公共 Host、只读工具 Schema、限流和输出上限，并通过真实代表调用、拒写、超时、重启、清理与用户验收。',),
    ),
    CatalogExpansionV3Adapter(
        project_id='agenticmail-agenticmail',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='bintocher-mcp-superset',
        availability='planned',
        decision_reason_code='planned-wave27-native-readonly-data-service',
        adaptation_wave=27,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('fixed-database-target', 'native-read-only-role', 'read-only-query-policy', 'query-and-output-limits'),
        limitations=('可继续评估固定协议、结构化目标和原生只读账号下的 describe/list/search/read-query 子集；DSN、管理操作、写查询和动态端点保持禁止，真实服务验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='chemiguel23-memorymesh',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('该产品依赖项目级持久化、保留/导出/删除、容量或模型费用配额及一次性写审批；Wave 21 基础完成前保持 planned，当前不创建运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='chroma-core-chroma-mcp',
        availability='planned',
        decision_reason_code='planned-wave27-native-readonly-data-service',
        adaptation_wave=27,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('fixed-database-target', 'native-read-only-role', 'read-only-query-policy', 'query-and-output-limits'),
        limitations=('可继续评估固定协议、结构化目标和原生只读账号下的 describe/list/search/read-query 子集；DSN、管理操作、写查询和动态端点保持禁止，真实服务验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='codeabra-iai-personal-memory-engine',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('该产品依赖项目级持久化、保留/导出/删除、容量或模型费用配额及一次性写审批；Wave 21 基础完成前保持 planned，当前不创建运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='confluentinc-mcp-confluent',
        availability='planned',
        decision_reason_code='planned-wave27-native-readonly-data-service',
        adaptation_wave=27,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('fixed-database-target', 'native-read-only-role', 'read-only-query-policy', 'query-and-output-limits'),
        limitations=('可继续评估固定协议、结构化目标和原生只读账号下的 describe/list/search/read-query 子集；DSN、管理操作、写查询和动态端点保持禁止，真实服务验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='frowningdev-django-orm-lens',
        availability='planned',
        decision_reason_code='planned-wave26-offline-file-or-deterministic-artifact',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('scoped-filesystem', 'network-disabled', 'artifact-cleanup', 'resource-limits'),
        limitations=('可继续评估断网、封存输入、确定性处理与服务端复制产物的文件子集；在路径隔离、资源限额、超时、清理和真实镜像验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='jtang613-ghidrassistmcp',
        availability='blocked',
        decision_reason_code='blocked-desktop-browser-or-device-control',
        adaptation_wave=24,
        connection_kind='desktop-bridge',
        risk='high',
        required_capabilities=('trusted-desktop-host', 'per-user-process-isolation'),
        limitations=('上游依赖桌面宿主、浏览器自动化、IDE/模拟器、设备控制或任意宿主路径；这些能力在多租户桌面宿主边界完成前继续冻结。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='king-of-the-grackles-reddit-research-mcp',
        availability='planned',
        decision_reason_code='planned-wave25-anonymous-public-read-contract',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('可继续评估匿名固定域名的公开搜索或元数据读取；在冻结上游版本、固定 Host、只读工具 Schema、限流与输出上限并完成真实代表调用前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='mark3labs-mcp-filesystem-server',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-controlled-capability',
        adaptation_wave=24,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'bounded-runtime-surface'),
        limitations=('该实现与已存在的受控浏览器、搜索、文件或代码索引能力重复，且不会提供更窄、更可验证的边界；转为 blocked/superseded，不创建第二套运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='mnemox-ai-tradememory-protocol',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('该产品依赖项目级持久化、保留/导出/删除、容量或模型费用配额及一次性写审批；Wave 21 基础完成前保持 planned，当前不创建运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='nakaokarei-swift-mcp-gui',
        availability='blocked',
        decision_reason_code='blocked-desktop-browser-or-device-control',
        adaptation_wave=24,
        connection_kind='desktop-bridge',
        risk='high',
        required_capabilities=('trusted-desktop-host', 'per-user-process-isolation'),
        limitations=('上游依赖桌面宿主、浏览器自动化、IDE/模拟器、设备控制或任意宿主路径；这些能力在多租户桌面宿主边界完成前继续冻结。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='ndthanhdev-mcp-browser-kit',
        availability='blocked',
        decision_reason_code='blocked-desktop-browser-or-device-control',
        adaptation_wave=24,
        connection_kind='desktop-bridge',
        risk='high',
        required_capabilities=('trusted-desktop-host', 'per-user-process-isolation'),
        limitations=('上游依赖桌面宿主、浏览器自动化、IDE/模拟器、设备控制或任意宿主路径；这些能力在多租户桌面宿主边界完成前继续冻结。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='openmf-mcp-mifosx',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='overpod-mcp-telegram',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='patsnap-patent-literature-search-mcp',
        availability='planned',
        decision_reason_code='planned-wave25-anonymous-public-read-contract',
        adaptation_wave=25,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('fixed-egress-policy', 'read-only-tool-policy', 'schema-drift-recovery', 'provider-rate-limit'),
        limitations=('可继续评估匿名固定域名的公开搜索或元数据读取；在冻结上游版本、固定 Host、只读工具 Schema、限流与输出上限并完成真实代表调用前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='portainer-portainer-mcp',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='quackbackio-quackback',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='riponcm-projectmem',
        availability='planned',
        decision_reason_code='planned-wave21-stateful-foundation-required',
        adaptation_wave=21,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('project-scoped-persistence', 'retention-export-delete-policy', 'storage-and-model-cost-quota', 'one-shot-write-approval'),
        limitations=('该产品依赖项目级持久化、保留/导出/删除、容量或模型费用配额及一次性写审批；Wave 21 基础完成前保持 planned，当前不创建运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='stape-io-google-tag-manager-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='the-momentum-apple-health-mcp-server',
        availability='planned',
        decision_reason_code='planned-wave26-offline-file-or-deterministic-artifact',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('scoped-filesystem', 'network-disabled', 'artifact-cleanup', 'resource-limits'),
        limitations=('可继续评估断网、封存输入、确定性处理与服务端复制产物的文件子集；在路径隔离、资源限额、超时、清理和真实镜像验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='traceloop-opentelemetry-mcp-server',
        availability='planned',
        decision_reason_code='planned-wave27-native-readonly-data-service',
        adaptation_wave=27,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('fixed-database-target', 'native-read-only-role', 'read-only-query-policy', 'query-and-output-limits'),
        limitations=('可继续评估固定协议、结构化目标和原生只读账号下的 describe/list/search/read-query 子集；DSN、管理操作、写查询和动态端点保持禁止，真实服务验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='victoriametrics-community-mcp-victoriametrics',
        availability='planned',
        decision_reason_code='planned-wave27-native-readonly-data-service',
        adaptation_wave=27,
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('fixed-database-target', 'native-read-only-role', 'read-only-query-policy', 'query-and-output-limits'),
        limitations=('可继续评估固定协议、结构化目标和原生只读账号下的 describe/list/search/read-query 子集；DSN、管理操作、写查询和动态端点保持禁止，真实服务验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='workopia-workopia-mcp',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='yuna0x0-hackmd-mcp',
        availability='blocked',
        decision_reason_code='blocked-account-cloud-write-or-management',
        adaptation_wave=24,
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('authenticated-user-context', 'tenant-isolation', 'write-approval'),
        limitations=('上游核心工具包含账号发布、资源写入、基础设施管理、通讯发送或金融操作；即使未来补齐 OAuth/多租户，只读之外的能力仍保持 blocked。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='yurineko73-godot-mcp-native',
        availability='blocked',
        decision_reason_code='blocked-desktop-browser-or-device-control',
        adaptation_wave=24,
        connection_kind='desktop-bridge',
        risk='high',
        required_capabilities=('trusted-desktop-host', 'per-user-process-isolation'),
        limitations=('上游依赖桌面宿主、浏览器自动化、IDE/模拟器、设备控制或任意宿主路径；这些能力在多租户桌面宿主边界完成前继续冻结。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='yusufkaraaslan-skill-seekers',
        availability='planned',
        decision_reason_code='planned-wave26-offline-file-or-deterministic-artifact',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('scoped-filesystem', 'network-disabled', 'artifact-cleanup', 'resource-limits'),
        limitations=('可继续评估断网、封存输入、确定性处理与服务端复制产物的文件子集；在路径隔离、资源限额、超时、清理和真实镜像验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='zinja-coder-apktool-mcp-server',
        availability='planned',
        decision_reason_code='planned-wave26-offline-file-or-deterministic-artifact',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('scoped-filesystem', 'network-disabled', 'artifact-cleanup', 'resource-limits'),
        limitations=('可继续评估断网、封存输入、确定性处理与服务端复制产物的文件子集；在路径隔离、资源限额、超时、清理和真实镜像验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='zubeidhendricks-youtube-mcp-server',
        availability='blocked',
        decision_reason_code='blocked-superseded-existing-controlled-capability',
        adaptation_wave=24,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'bounded-runtime-surface'),
        limitations=('该实现与已存在的受控浏览器、搜索、文件或代码索引能力重复，且不会提供更窄、更可验证的边界；转为 blocked/superseded，不创建第二套运行时。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='ai-xiaodao-ai-browser-mcp',
        availability='blocked',
        decision_reason_code='blocked-desktop-browser-or-device-control',
        adaptation_wave=24,
        connection_kind='desktop-bridge',
        risk='high',
        required_capabilities=('trusted-desktop-host', 'per-user-process-isolation'),
        limitations=('上游依赖桌面宿主、浏览器自动化、IDE/模拟器、设备控制或任意宿主路径；这些能力在多租户桌面宿主边界完成前继续冻结。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
    CatalogExpansionV3Adapter(
        project_id='aimino-tech-opendocswork-mcp',
        availability='planned',
        decision_reason_code='planned-wave26-offline-file-or-deterministic-artifact',
        adaptation_wave=26,
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('scoped-filesystem', 'network-disabled', 'artifact-cleanup', 'resource-limits'),
        limitations=('可继续评估断网、封存输入、确定性处理与服务端复制产物的文件子集；在路径隔离、资源限额、超时、清理和真实镜像验收前保持 planned。', '当前仅登记产品身份与适配判定；没有命令、端点、凭据槽、工具策略、运行镜像或默认 allowlist，任何功能开关都不能使该条目可执行。'),
    ),
)
