"""Generated non-executable manifests for the approved MCP catalog expansion."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class CatalogExpansionV2Adapter:
    project_id: str
    connection_kind: str
    risk: str
    required_capabilities: tuple[str, ...]
    limitations: tuple[str, ...]


CATALOG_EXPANSION_V2_ADAPTERS = (
    CatalogExpansionV2Adapter(
        project_id='deusdata-codebase-memory-mcp',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='0xmassi-webclaw',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='co-browser-browser-use-mcp-server',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='sipyourdrink-ltd-bernstein',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='beever-ai-beever-atlas',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='googleapis-genai-toolbox',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='flox-foundation-flox-mcp',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='us-crw',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='fatwang2-search1api-mcp',
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='markuspfundstein-mcp-obsidian',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='mrexodia-ida-pro-mcp',
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('仅完成双源目录身份核验；尚无可信桌面宿主、实例所有权证明或逐应用授权。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='qdrant-mcp-server-qdrant',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='wonderwhy-er-desktopcommandermcp',
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('仅完成双源目录身份核验；尚无可信桌面宿主、实例所有权证明或逐应用授权。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='blazickjp-arxiv-mcp-server',
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='goldentrii-agentrecall',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='zcaceres-markdownify-mcp',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='benborla-mcp-server-mysql',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='samuelgursky-davinci-resolve-mcp',
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('仅完成双源目录身份核验；尚无可信桌面宿主、实例所有权证明或逐应用授权。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='aas-ee-open-websearch',
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='chigwell-telegram-mcp',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='codergamester-mcp-unity',
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('仅完成双源目录身份核验；尚无可信桌面宿主、实例所有权证明或逐应用授权。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='flux159-mcp-server-kubernetes',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='genomoncology-biomcp',
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='nickclyde-duckduckgo-mcp-server',
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='oraios-serena',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='taylorwilsdon-google-workspace-mcp',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='mnemox-ai-idea-reality-mcp',
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='chopratejas-headroom',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='designcomputer-mysql-mcp-server',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='freepeak-db-mcp-server',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='ihor-sokoliuk-mcp-searxng',
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='inditextech-mcp-teams-server',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='kagisearch-kagimcp',
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='mcpdotdirect-evm-mcp-server',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='shashankss1205-codegraphcontext',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='tuanle96-mcp-odoo',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='ckreiling-mcp-server-docker',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='coding-solo-godot-mcp',
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('仅完成双源目录身份核验；尚无可信桌面宿主、实例所有权证明或逐应用授权。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='cyberchitta-llm-context-py',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='haris-musa-excel-mcp-server',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='idosal-git-mcp',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='nteract-semiotic',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='public-ui-kolibri',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='radareorg-radare2-mcp',
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('仅完成双源目录身份核验；尚无可信桌面宿主、实例所有权证明或逐应用授权。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='skyhook-io-radar',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='suekou-mcp-notion-server',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='xing5-mcp-google-sheets',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='comet-ml-opik-mcp',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='quarkiverse-quarkus-mcp-servers-filesystem',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='quarkiverse-quarkus-mcp-servers-jdbc',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='samvallad33-vestige',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='vivekvells-mcp-pandoc',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='yolfinance-yolfi-agent',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='zilliztech-mcp-server-milvus',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='alexei-led-k8s-mcp-server',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='anypost-emailmd',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='brave-brave-search-mcp-server',
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='cablate-mcp-google-map',
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='diivi-aseprite-mcp',
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('仅完成双源目录身份核验；尚无可信桌面宿主、实例所有权证明或逐应用授权。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='docker-hub-mcp',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='integromat-make-mcp-server',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='ivanmurzak-unity-mcp',
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('仅完成双源目录身份核验；尚无可信桌面宿主、实例所有权证明或逐应用授权。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='juyterman1000-entroly',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='livetennisapi-livetennisapi-mcp',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='neo4j-contrib-mcp-neo4j',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='pab1it0-prometheus-mcp-server',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='pv-bhat-vibe-check-mcp-server',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='r-huijts-strava-mcp',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='runekaagaard-mcp-alchemy',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='safedep-vet',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('ephemeral-code-sandbox', 'scoped-filesystem', 'terminal-action-approval'),
        limitations=('仅完成双源目录身份核验；尚未冻结输入范围、只读工具子集、进程隔离与终止性操作审批。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='stack-chan-stack-chan',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='tacticlaunch-mcp-linear',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='tiberriver256-mcp-server-azure-devops',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='xquik-dev-x-twitter-scraper',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='alexei-led-aws-mcp-server',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='arcadedata-arcadedb',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='carterlasalle-mac-messages-mcp',
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('仅完成双源目录身份核验；尚无可信桌面宿主、实例所有权证明或逐应用授权。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='cr7258-elasticsearch-mcp-server',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='datalayer-jupyter-mcp-server',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='emiliaprotocol-emilia-protocol',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('ephemeral-code-sandbox', 'scoped-filesystem', 'terminal-action-approval'),
        limitations=('仅完成双源目录身份核验；尚未冻结输入范围、只读工具子集、进程隔离与终止性操作审批。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='eyalzh-browser-control-mcp',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='ferdousbhai-investor-agent',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='jpisnice-shadcn-ui-mcp-server',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='kiliczsh-mcp-mongo-server',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='lpigeon-ros-mcp-server',
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('仅完成双源目录身份核验；尚无可信桌面宿主、实例所有权证明或逐应用授权。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='nwiizo-tfmcp',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='vectorize-io-vectorize-mcp-server',
        connection_kind='remote-mcp',
        risk='medium',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='antvis-mcp-server-chart',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='caol64-wenyan-mcp',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='dataeval-dingo',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='g0t4-mcp-server-commands',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='keboola-keboola-mcp-server',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='line-line-bot-mcp-server',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='ozgurcd-gograph',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='patdolitse-piia-engram',
        connection_kind='sandboxed-stdio',
        risk='medium',
        required_capabilities=('maintained-upstream-contract', 'scoped-filesystem', 'resource-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结上游版本、工具 Schema、文件范围与资源上限。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='taisly-agent',
        connection_kind='remote-mcp',
        risk='high',
        required_capabilities=('fixed-saas-contract', 'fixed-egress-policy', 'encrypted-credential-binding'),
        limitations=('仅完成双源目录身份核验；尚未冻结远程传输、服务域名、凭据槽、工具副作用与限流策略。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='zinja-coder-jadx-ai-mcp',
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('仅完成双源目录身份核验；尚无可信桌面宿主、实例所有权证明或逐应用授权。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='alexander-zuev-supabase-mcp-server',
        connection_kind='sandboxed-stdio',
        risk='high',
        required_capabilities=('database-read-only-policy', 'database-target-validation', 'query-limits'),
        limitations=('仅完成双源目录身份核验；尚未冻结数据库目标、原生只读模式、查询上限与凭据作用域。', '当前没有命令、端点、凭据槽、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='bx33661-wireshark-mcp',
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('仅完成双源目录身份核验；尚无可信桌面宿主、实例所有权证明或逐应用授权。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
    CatalogExpansionV2Adapter(
        project_id='bytedance-ui-tars-desktop-browser',
        connection_kind='desktop-bridge',
        risk='critical',
        required_capabilities=('versioned-desktop-bridge', 'per-app-consent'),
        limitations=('仅完成双源目录身份核验；尚无可信桌面宿主、实例所有权证明或逐应用授权。', '当前没有命令、端点、工具或连接入口，环境功能开关也不能使该条目可执行。'),
    ),
)

CATALOG_EXPANSION_V2_IDS = tuple(
    item.project_id for item in CATALOG_EXPANSION_V2_ADAPTERS
)
